package net.solace.api.movement.pathfinder.model;

import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import net.runelite.api.Quest;
import net.runelite.api.coords.WorldPoint;
import net.solace.api.Static;
import net.solace.api.domain.items.IItem;
import net.solace.api.domain.widgets.IWidget;
import net.solace.api.movement.pathfinder.model.Transport;
import net.solace.api.movement.pathfinder.model.requirement.ItemRequirement;
import net.solace.api.movement.pathfinder.model.requirement.QuestRequirement;
import net.solace.api.movement.pathfinder.model.requirement.Reduction;
import net.solace.api.movement.pathfinder.model.requirement.Requirement;
import net.solace.api.movement.pathfinder.model.requirement.Requirements;
import net.solace.api.movement.pathfinder.model.requirement.SkillRequirement;
import net.solace.api.movement.pathfinder.model.requirement.VarRequirement;
import net.solace.api.widgets.EquipmentSlot;

public enum CharterShip {
    ALDARIN_TO_BRIMHAVEN(ShipLocation.ALDARIN, ShipLocation.BRIMHAVEN, 2500, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_CATHERBY(ShipLocation.ALDARIN, ShipLocation.CATHERBY, 2500, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_CIVITAS_ILLA_FORTIS(ShipLocation.ALDARIN, ShipLocation.CIVITAS_ILLA_FORTIS, 600, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_CORSAIR_COVE(ShipLocation.ALDARIN, ShipLocation.CORSAIR_COVE, 2100, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_DEEPFIN_POINT(ShipLocation.ALDARIN, ShipLocation.DEEPFIN_POINT, 1200, Requirement.VISITED_VARLAMORE, Requirement.VISITED_DEEPFIN_POINT),
    ALDARIN_TO_LANDS_END(ShipLocation.ALDARIN, ShipLocation.LANDS_END, 900, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    ALDARIN_TO_MOS_LE_HARMLESS(ShipLocation.ALDARIN, ShipLocation.MOS_LE_HARMLESS, 4700, Requirement.VISITED_VARLAMORE, Requirement.CABIN_FEVER_QUEST),
    ALDARIN_TO_MUSA_POINT(ShipLocation.ALDARIN, ShipLocation.MUSA_POINT, 3000, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_PANDEMONIUM(ShipLocation.ALDARIN, ShipLocation.PANDEMONIUM, 3000, Requirement.VISITED_VARLAMORE, Requirement.PANDEMONIUM_COMPLETED),
    ALDARIN_TO_PORT_KHAZARD(ShipLocation.ALDARIN, ShipLocation.PORT_KHAZARD, 2300, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_PORT_PHASMATYS(ShipLocation.ALDARIN, ShipLocation.PORT_PHASMATYS, 4500, Requirement.VISITED_VARLAMORE, Requirement.VISITED_MORYTANIA),
    ALDARIN_TO_PORT_PISCARILIUS(ShipLocation.ALDARIN, ShipLocation.PORT_PISCARILIUS, 1100, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    ALDARIN_TO_PORT_ROBERTS(ShipLocation.ALDARIN, ShipLocation.PORT_ROBERTS, 1400, Requirement.VISITED_VARLAMORE, Requirement.VISITED_PORT_ROBERTS),
    ALDARIN_TO_PORT_SARIM(ShipLocation.ALDARIN, ShipLocation.PORT_SARIM, 3100, Requirement.VISITED_VARLAMORE),
    ALDARIN_TO_PORT_TYRAS(ShipLocation.ALDARIN, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_VARLAMORE, Requirement.REGICIDE_QUEST),
    ALDARIN_TO_PRIFDDINAS(ShipLocation.ALDARIN, ShipLocation.PRIFDDINAS, 1800, Requirement.VISITED_VARLAMORE, Requirement.SONG_OF_THE_ELVES_QUEST),
    ALDARIN_TO_SHIPYARD(ShipLocation.ALDARIN, ShipLocation.SHIPYARD, 3100, Requirement.VISITED_VARLAMORE, Requirement.MONKEY_MADNESS_I_FINISHED),
    BRIMHAVEN_TO_ALDARIN(ShipLocation.BRIMHAVEN, ShipLocation.ALDARIN, 2500, Requirement.VISITED_VARLAMORE),
    BRIMHAVEN_TO_CATHERBY(ShipLocation.BRIMHAVEN, ShipLocation.CATHERBY, 480, new Requirement[0]),
    BRIMHAVEN_TO_CIVITAS_ILLA_FORTIS(ShipLocation.BRIMHAVEN, ShipLocation.CIVITAS_ILLA_FORTIS, 2400, Requirement.VISITED_VARLAMORE),
    BRIMHAVEN_TO_CORSAIR_COVE(ShipLocation.BRIMHAVEN, ShipLocation.CORSAIR_COVE, 680, new Requirement[0]),
    BRIMHAVEN_TO_DEEPFIN_POINT(ShipLocation.BRIMHAVEN, ShipLocation.DEEPFIN_POINT, 2000, Requirement.VISITED_DEEPFIN_POINT),
    BRIMHAVEN_TO_LANDS_END(ShipLocation.BRIMHAVEN, ShipLocation.LANDS_END, 2200, Requirement.VISITED_KOUREND),
    BRIMHAVEN_TO_MOS_LE_HARMLESS(ShipLocation.BRIMHAVEN, ShipLocation.MOS_LE_HARMLESS, 3900, Requirement.CABIN_FEVER_QUEST),
    BRIMHAVEN_TO_MUSA_POINT(ShipLocation.BRIMHAVEN, ShipLocation.MUSA_POINT, 480, new Requirement[0]),
    BRIMHAVEN_TO_PANDEMONIUM(ShipLocation.BRIMHAVEN, ShipLocation.PANDEMONIUM, 400, Requirement.PANDEMONIUM_COMPLETED),
    BRIMHAVEN_TO_PORT_KHAZARD(ShipLocation.BRIMHAVEN, ShipLocation.PORT_KHAZARD, 400, new Requirement[0]),
    BRIMHAVEN_TO_PORT_PHASMATYS(ShipLocation.BRIMHAVEN, ShipLocation.PORT_PHASMATYS, 2900, Requirement.VISITED_MORYTANIA),
    BRIMHAVEN_TO_PORT_PISCARILIUS(ShipLocation.BRIMHAVEN, ShipLocation.PORT_PISCARILIUS, 2000, Requirement.VISITED_KOUREND),
    BRIMHAVEN_TO_PORT_ROBERTS(ShipLocation.BRIMHAVEN, ShipLocation.PORT_ROBERTS, 3200, Requirement.VISITED_PORT_ROBERTS),
    BRIMHAVEN_TO_PORT_SARIM(ShipLocation.BRIMHAVEN, ShipLocation.PORT_SARIM, 1600, new Requirement[0]),
    BRIMHAVEN_TO_PORT_TYRAS(ShipLocation.BRIMHAVEN, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    BRIMHAVEN_TO_PRIFDDINAS(ShipLocation.BRIMHAVEN, ShipLocation.PRIFDDINAS, 3450, Requirement.SONG_OF_THE_ELVES_QUEST),
    BRIMHAVEN_TO_SHIPYARD(ShipLocation.BRIMHAVEN, ShipLocation.SHIPYARD, 400, Requirement.MONKEY_MADNESS_I_FINISHED),
    BRIMHAVEN_TO_SUNSET_COAST(ShipLocation.BRIMHAVEN, ShipLocation.SUNSET_COAST, 2500, Requirement.VISITED_VARLAMORE),
    CATHERBY_TO_ALDARIN(ShipLocation.CATHERBY, ShipLocation.ALDARIN, 2500, Requirement.VISITED_VARLAMORE),
    CATHERBY_TO_BRIMHAVEN(ShipLocation.CATHERBY, ShipLocation.BRIMHAVEN, 480, new Requirement[0]),
    CATHERBY_TO_CIVITAS_ILLA_FORTIS(ShipLocation.CATHERBY, ShipLocation.CIVITAS_ILLA_FORTIS, 2400, Requirement.VISITED_VARLAMORE),
    CATHERBY_TO_CORSAIR_COVE(ShipLocation.CATHERBY, ShipLocation.CORSAIR_COVE, 1000, new Requirement[0]),
    CATHERBY_TO_DEEPFIN_POINT(ShipLocation.CATHERBY, ShipLocation.DEEPFIN_POINT, 2200, Requirement.VISITED_DEEPFIN_POINT),
    CATHERBY_TO_LANDS_END(ShipLocation.CATHERBY, ShipLocation.LANDS_END, 2200, Requirement.VISITED_KOUREND),
    CATHERBY_TO_MOS_LE_HARMLESS(ShipLocation.CATHERBY, ShipLocation.MOS_LE_HARMLESS, 2500, Requirement.CABIN_FEVER_QUEST),
    CATHERBY_TO_MUSA_POINT(ShipLocation.CATHERBY, ShipLocation.MUSA_POINT, 480, new Requirement[0]),
    CATHERBY_TO_PANDEMONIUM(ShipLocation.CATHERBY, ShipLocation.PANDEMONIUM, 1200, Requirement.PANDEMONIUM_COMPLETED),
    CATHERBY_TO_PORT_KHAZARD(ShipLocation.CATHERBY, ShipLocation.PORT_KHAZARD, 1600, new Requirement[0]),
    CATHERBY_TO_PORT_PHASMATYS(ShipLocation.CATHERBY, ShipLocation.PORT_PHASMATYS, 3500, Requirement.VISITED_MORYTANIA),
    CATHERBY_TO_PORT_PISCARILIUS(ShipLocation.CATHERBY, ShipLocation.PORT_PISCARILIUS, 2000, Requirement.VISITED_KOUREND),
    CATHERBY_TO_PORT_ROBERTS(ShipLocation.CATHERBY, ShipLocation.PORT_ROBERTS, 3400, Requirement.VISITED_PORT_ROBERTS),
    CATHERBY_TO_PORT_SARIM(ShipLocation.CATHERBY, ShipLocation.PORT_SARIM, 1000, new Requirement[0]),
    CATHERBY_TO_PORT_TYRAS(ShipLocation.CATHERBY, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    CATHERBY_TO_PRIFDDINAS(ShipLocation.CATHERBY, ShipLocation.PRIFDDINAS, 3560, Requirement.SONG_OF_THE_ELVES_QUEST),
    CATHERBY_TO_SHIPYARD(ShipLocation.CATHERBY, ShipLocation.SHIPYARD, 1600, Requirement.MONKEY_MADNESS_I_FINISHED),
    CATHERBY_TO_SUNSET_COAST(ShipLocation.CATHERBY, ShipLocation.SUNSET_COAST, 2500, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_ALDARIN(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.ALDARIN, 600, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_BRIMHAVEN(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.BRIMHAVEN, 2400, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_CATHERBY(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.CATHERBY, 2400, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_CORSAIR_COVE(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.CORSAIR_COVE, 2000, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_DEEPFIN_POINT(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.DEEPFIN_POINT, 1200, Requirement.VISITED_VARLAMORE, Requirement.VISITED_DEEPFIN_POINT),
    CIVITAS_ILLA_FORTIS_TO_LANDS_END(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.LANDS_END, 800, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    CIVITAS_ILLA_FORTIS_TO_MOS_LE_HARMLESS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.MOS_LE_HARMLESS, 4600, Requirement.VISITED_VARLAMORE, Requirement.CABIN_FEVER_QUEST),
    CIVITAS_ILLA_FORTIS_TO_MUSA_POINT(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.MUSA_POINT, 2900, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_PANDEMONIUM(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PANDEMONIUM, 2800, Requirement.VISITED_VARLAMORE, Requirement.PANDEMONIUM_COMPLETED),
    CIVITAS_ILLA_FORTIS_TO_PORT_KHAZARD(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_KHAZARD, 2200, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_PORT_PHASMATYS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_PHASMATYS, 4400, Requirement.VISITED_VARLAMORE, Requirement.VISITED_MORYTANIA),
    CIVITAS_ILLA_FORTIS_TO_PORT_PISCARILIUS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_PISCARILIUS, 1000, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    CIVITAS_ILLA_FORTIS_TO_PORT_ROBERTS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_ROBERTS, 600, Requirement.VISITED_VARLAMORE, Requirement.VISITED_PORT_ROBERTS),
    CIVITAS_ILLA_FORTIS_TO_PORT_SARIM(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_SARIM, 3000, Requirement.VISITED_VARLAMORE),
    CIVITAS_ILLA_FORTIS_TO_PORT_TYRAS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_VARLAMORE, Requirement.REGICIDE_QUEST),
    CIVITAS_ILLA_FORTIS_TO_PRIFDDINAS(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.PRIFDDINAS, 1700, Requirement.VISITED_VARLAMORE, Requirement.SONG_OF_THE_ELVES_QUEST),
    CIVITAS_ILLA_FORTIS_TO_SHIPYARD(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.SHIPYARD, 3000, Requirement.VISITED_VARLAMORE, Requirement.MONKEY_MADNESS_I_FINISHED),
    CIVITAS_ILLA_FORTIS_TO_SUNSET_COAST(ShipLocation.CIVITAS_ILLA_FORTIS, ShipLocation.SUNSET_COAST, 500, Requirement.VISITED_VARLAMORE),
    CORSAIR_COVE_TO_ALDARIN(ShipLocation.CORSAIR_COVE, ShipLocation.ALDARIN, 2100, Requirement.VISITED_VARLAMORE),
    CORSAIR_COVE_TO_BRIMHAVEN(ShipLocation.CORSAIR_COVE, ShipLocation.BRIMHAVEN, 680, new Requirement[0]),
    CORSAIR_COVE_TO_CATHERBY(ShipLocation.CORSAIR_COVE, ShipLocation.CATHERBY, 1000, new Requirement[0]),
    CORSAIR_COVE_TO_CIVITAS_ILLA_FORTIS(ShipLocation.CORSAIR_COVE, ShipLocation.CIVITAS_ILLA_FORTIS, 2000, Requirement.VISITED_VARLAMORE),
    CORSAIR_COVE_TO_DEEPFIN_POINT(ShipLocation.CORSAIR_COVE, ShipLocation.DEEPFIN_POINT, 1600, Requirement.VISITED_DEEPFIN_POINT),
    CORSAIR_COVE_TO_LANDS_END(ShipLocation.CORSAIR_COVE, ShipLocation.LANDS_END, 1800, Requirement.VISITED_KOUREND),
    CORSAIR_COVE_TO_MOS_LE_HARMLESS(ShipLocation.CORSAIR_COVE, ShipLocation.MOS_LE_HARMLESS, 4080, Requirement.CABIN_FEVER_QUEST),
    CORSAIR_COVE_TO_MUSA_POINT(ShipLocation.CORSAIR_COVE, ShipLocation.MUSA_POINT, 800, new Requirement[0]),
    CORSAIR_COVE_TO_PANDEMONIUM(ShipLocation.CORSAIR_COVE, ShipLocation.PANDEMONIUM, 800, Requirement.PANDEMONIUM_COMPLETED),
    CORSAIR_COVE_TO_PORT_KHAZARD(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_KHAZARD, 600, new Requirement[0]),
    CORSAIR_COVE_TO_PORT_PHASMATYS(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_PHASMATYS, 4040, Requirement.VISITED_MORYTANIA),
    CORSAIR_COVE_TO_PORT_PISCARILIUS(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_PISCARILIUS, 1500, Requirement.VISITED_KOUREND),
    CORSAIR_COVE_TO_PORT_ROBERTS(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_ROBERTS, 2200, Requirement.VISITED_PORT_ROBERTS),
    CORSAIR_COVE_TO_PORT_SARIM(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_SARIM, 1200, new Requirement[0]),
    CORSAIR_COVE_TO_PORT_TYRAS(ShipLocation.CORSAIR_COVE, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    CORSAIR_COVE_TO_PRIFDDINAS(ShipLocation.CORSAIR_COVE, ShipLocation.PRIFDDINAS, 1420, Requirement.SONG_OF_THE_ELVES_QUEST),
    CORSAIR_COVE_TO_SHIPYARD(ShipLocation.CORSAIR_COVE, ShipLocation.SHIPYARD, 800, Requirement.MONKEY_MADNESS_I_FINISHED),
    CORSAIR_COVE_TO_SUNSET_COAST(ShipLocation.CORSAIR_COVE, ShipLocation.SUNSET_COAST, 2100, Requirement.VISITED_VARLAMORE),
    DEEPFIN_POINT_TO_ALDARIN(ShipLocation.DEEPFIN_POINT, ShipLocation.ALDARIN, 1200, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_VARLAMORE),
    DEEPFIN_POINT_TO_BRIMHAVEN(ShipLocation.DEEPFIN_POINT, ShipLocation.BRIMHAVEN, 2000, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_CATHERBY(ShipLocation.DEEPFIN_POINT, ShipLocation.CATHERBY, 2200, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_CIVITAS_ILLA_FORTIS(ShipLocation.DEEPFIN_POINT, ShipLocation.CIVITAS_ILLA_FORTIS, 1200, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_VARLAMORE),
    DEEPFIN_POINT_TO_CORSAIR_COVE(ShipLocation.DEEPFIN_POINT, ShipLocation.CORSAIR_COVE, 1600, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_LANDS_END(ShipLocation.DEEPFIN_POINT, ShipLocation.LANDS_END, 1400, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_KOUREND),
    DEEPFIN_POINT_TO_MOS_LE_HARMLESS(ShipLocation.DEEPFIN_POINT, ShipLocation.MOS_LE_HARMLESS, 3200, Requirement.VISITED_DEEPFIN_POINT, Requirement.CABIN_FEVER_QUEST),
    DEEPFIN_POINT_TO_MUSA_POINT(ShipLocation.DEEPFIN_POINT, ShipLocation.MUSA_POINT, 2400, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_PANDEMONIUM(ShipLocation.DEEPFIN_POINT, ShipLocation.PANDEMONIUM, 2800, Requirement.VISITED_DEEPFIN_POINT, Requirement.PANDEMONIUM_COMPLETED),
    DEEPFIN_POINT_TO_PORT_KHAZARD(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_KHAZARD, 1800, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_PORT_PHASMATYS(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_PHASMATYS, 3400, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_MORYTANIA),
    DEEPFIN_POINT_TO_PORT_PISCARILIUS(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_PISCARILIUS, 1600, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_KOUREND),
    DEEPFIN_POINT_TO_PORT_ROBERTS(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_ROBERTS, 1000, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_PORT_ROBERTS),
    DEEPFIN_POINT_TO_PORT_SARIM(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_SARIM, 2600, Requirement.VISITED_DEEPFIN_POINT),
    DEEPFIN_POINT_TO_PORT_TYRAS(ShipLocation.DEEPFIN_POINT, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_DEEPFIN_POINT, Requirement.REGICIDE_QUEST),
    DEEPFIN_POINT_TO_PRIFDDINAS(ShipLocation.DEEPFIN_POINT, ShipLocation.PRIFDDINAS, 1200, Requirement.VISITED_DEEPFIN_POINT, Requirement.SONG_OF_THE_ELVES_QUEST),
    DEEPFIN_POINT_TO_SHIPYARD(ShipLocation.DEEPFIN_POINT, ShipLocation.SHIPYARD, 2800, Requirement.VISITED_DEEPFIN_POINT, Requirement.MONKEY_MADNESS_I_FINISHED),
    DEEPFIN_POINT_TO_SUNSET_COAST(ShipLocation.DEEPFIN_POINT, ShipLocation.SUNSET_COAST, 1200, Requirement.VISITED_DEEPFIN_POINT, Requirement.VISITED_VARLAMORE),
    LANDS_END_TO_ALDARIN(ShipLocation.LANDS_END, ShipLocation.ALDARIN, 900, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    LANDS_END_TO_BRIMHAVEN(ShipLocation.LANDS_END, ShipLocation.BRIMHAVEN, 2200, Requirement.VISITED_KOUREND),
    LANDS_END_TO_CATHERBY(ShipLocation.LANDS_END, ShipLocation.CATHERBY, 2200, Requirement.VISITED_KOUREND),
    LANDS_END_TO_CIVITAS_ILLA_FORTIS(ShipLocation.LANDS_END, ShipLocation.CIVITAS_ILLA_FORTIS, 800, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    LANDS_END_TO_CORSAIR_COVE(ShipLocation.LANDS_END, ShipLocation.CORSAIR_COVE, 1800, Requirement.VISITED_KOUREND),
    LANDS_END_TO_DEEPFIN_POINT(ShipLocation.LANDS_END, ShipLocation.DEEPFIN_POINT, 1400, Requirement.VISITED_KOUREND, Requirement.VISITED_DEEPFIN_POINT),
    LANDS_END_TO_MOS_LE_HARMLESS(ShipLocation.LANDS_END, ShipLocation.MOS_LE_HARMLESS, 4400, Requirement.VISITED_KOUREND, Requirement.CABIN_FEVER_QUEST),
    LANDS_END_TO_MUSA_POINT(ShipLocation.LANDS_END, ShipLocation.MUSA_POINT, 2700, Requirement.VISITED_KOUREND),
    LANDS_END_TO_PANDEMONIUM(ShipLocation.LANDS_END, ShipLocation.PANDEMONIUM, 2600, Requirement.VISITED_KOUREND, Requirement.PANDEMONIUM_COMPLETED),
    LANDS_END_TO_PORT_KHAZARD(ShipLocation.LANDS_END, ShipLocation.PORT_KHAZARD, 2000, Requirement.VISITED_KOUREND),
    LANDS_END_TO_PORT_PHASMATYS(ShipLocation.LANDS_END, ShipLocation.PORT_PHASMATYS, 4200, Requirement.VISITED_KOUREND, Requirement.VISITED_MORYTANIA),
    LANDS_END_TO_PORT_ROBERTS(ShipLocation.LANDS_END, ShipLocation.PORT_ROBERTS, 800, Requirement.VISITED_KOUREND, Requirement.VISITED_PORT_ROBERTS),
    LANDS_END_TO_PORT_TYRAS(ShipLocation.LANDS_END, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_KOUREND, Requirement.REGICIDE_QUEST),
    LANDS_END_TO_PRIFDDINAS(ShipLocation.LANDS_END, ShipLocation.PRIFDDINAS, 1500, Requirement.VISITED_KOUREND, Requirement.SONG_OF_THE_ELVES_QUEST),
    LANDS_END_TO_SHIPYARD(ShipLocation.LANDS_END, ShipLocation.SHIPYARD, 2800, Requirement.VISITED_KOUREND, Requirement.MONKEY_MADNESS_I_FINISHED),
    LANDS_END_TO_SUNSET_COAST(ShipLocation.LANDS_END, ShipLocation.SUNSET_COAST, 900, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    MOS_LE_HARMLESS_TO_ALDARIN(ShipLocation.MOS_LE_HARMLESS, ShipLocation.ALDARIN, 4700, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_VARLAMORE),
    MOS_LE_HARMLESS_TO_BRIMHAVEN(ShipLocation.MOS_LE_HARMLESS, ShipLocation.BRIMHAVEN, 3900, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_CATHERBY(ShipLocation.MOS_LE_HARMLESS, ShipLocation.CATHERBY, 2500, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.MOS_LE_HARMLESS, ShipLocation.CIVITAS_ILLA_FORTIS, 4600, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_VARLAMORE),
    MOS_LE_HARMLESS_TO_CORSAIR_COVE(ShipLocation.MOS_LE_HARMLESS, ShipLocation.CORSAIR_COVE, 4080, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_DEEPFIN_POINT(ShipLocation.MOS_LE_HARMLESS, ShipLocation.DEEPFIN_POINT, 3200, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_DEEPFIN_POINT),
    MOS_LE_HARMLESS_TO_LANDS_END(ShipLocation.MOS_LE_HARMLESS, ShipLocation.LANDS_END, 4400, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_KOUREND),
    MOS_LE_HARMLESS_TO_MUSA_POINT(ShipLocation.MOS_LE_HARMLESS, ShipLocation.MUSA_POINT, 4100, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_PANDEMONIUM(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PANDEMONIUM, 1000, Requirement.CABIN_FEVER_QUEST, Requirement.PANDEMONIUM_COMPLETED),
    MOS_LE_HARMLESS_TO_PORT_KHAZARD(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PORT_KHAZARD, 1100, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_PORT_PISCARILIUS(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PORT_PISCARILIUS, 4200, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_KOUREND),
    MOS_LE_HARMLESS_TO_PORT_ROBERTS(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PORT_ROBERTS, 4400, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_PORT_ROBERTS),
    MOS_LE_HARMLESS_TO_PORT_SARIM(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PORT_SARIM, 1300, Requirement.CABIN_FEVER_QUEST),
    MOS_LE_HARMLESS_TO_PORT_TYRAS(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PORT_TYRAS, 3200, Requirement.CABIN_FEVER_QUEST, Requirement.REGICIDE_QUEST),
    MOS_LE_HARMLESS_TO_PRIFDDINAS(ShipLocation.MOS_LE_HARMLESS, ShipLocation.PRIFDDINAS, 4950, Requirement.CABIN_FEVER_QUEST, Requirement.SONG_OF_THE_ELVES_QUEST),
    MOS_LE_HARMLESS_TO_SHIPYARD(ShipLocation.MOS_LE_HARMLESS, ShipLocation.SHIPYARD, 1100, Requirement.CABIN_FEVER_QUEST, Requirement.MONKEY_MADNESS_I_FINISHED),
    MOS_LE_HARMLESS_TO_SUNSET_COAST(ShipLocation.MOS_LE_HARMLESS, ShipLocation.SUNSET_COAST, 4700, Requirement.CABIN_FEVER_QUEST, Requirement.VISITED_VARLAMORE),
    MUSA_POINT_TO_ALDARIN(ShipLocation.MUSA_POINT, ShipLocation.ALDARIN, 3000, Requirement.VISITED_VARLAMORE),
    MUSA_POINT_TO_BRIMHAVEN(ShipLocation.MUSA_POINT, ShipLocation.BRIMHAVEN, 480, new Requirement[0]),
    MUSA_POINT_TO_CATHERBY(ShipLocation.MUSA_POINT, ShipLocation.CATHERBY, 480, new Requirement[0]),
    MUSA_POINT_TO_CIVITAS_ILLA_FORTIS(ShipLocation.MUSA_POINT, ShipLocation.CIVITAS_ILLA_FORTIS, 2900, Requirement.VISITED_VARLAMORE),
    MUSA_POINT_TO_CORSAIR_COVE(ShipLocation.MUSA_POINT, ShipLocation.CORSAIR_COVE, 800, new Requirement[0]),
    MUSA_POINT_TO_DEEPFIN_POINT(ShipLocation.MUSA_POINT, ShipLocation.DEEPFIN_POINT, 2400, Requirement.VISITED_DEEPFIN_POINT),
    MUSA_POINT_TO_LANDS_END(ShipLocation.MUSA_POINT, ShipLocation.LANDS_END, 2700, Requirement.VISITED_KOUREND),
    MUSA_POINT_TO_MOS_LE_HARMLESS(ShipLocation.MUSA_POINT, ShipLocation.MOS_LE_HARMLESS, 4100, Requirement.CABIN_FEVER_QUEST),
    MUSA_POINT_TO_PORT_KHAZARD(ShipLocation.MUSA_POINT, ShipLocation.PORT_KHAZARD, 400, new Requirement[0]),
    MUSA_POINT_TO_PORT_PHASMATYS(ShipLocation.MUSA_POINT, ShipLocation.PORT_PHASMATYS, 1100, Requirement.VISITED_MORYTANIA),
    MUSA_POINT_TO_PORT_PISCARILIUS(ShipLocation.MUSA_POINT, ShipLocation.PORT_PISCARILIUS, 2500, Requirement.VISITED_KOUREND),
    MUSA_POINT_TO_PORT_ROBERTS(ShipLocation.MUSA_POINT, ShipLocation.PORT_ROBERTS, 3500, Requirement.VISITED_PORT_ROBERTS),
    MUSA_POINT_TO_PORT_TYRAS(ShipLocation.MUSA_POINT, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    MUSA_POINT_TO_PRIFDDINAS(ShipLocation.MUSA_POINT, ShipLocation.PRIFDDINAS, 4400, Requirement.SONG_OF_THE_ELVES_QUEST),
    MUSA_POINT_TO_SHIPYARD(ShipLocation.MUSA_POINT, ShipLocation.SHIPYARD, 200, Requirement.MONKEY_MADNESS_I_FINISHED),
    MUSA_POINT_TO_SUNSET_COAST(ShipLocation.MUSA_POINT, ShipLocation.SUNSET_COAST, 3000, Requirement.VISITED_VARLAMORE),
    PANDEMONIUM_TO_ALDARIN(ShipLocation.PANDEMONIUM, ShipLocation.ALDARIN, 3000, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_VARLAMORE),
    PANDEMONIUM_TO_BRIMHAVEN(ShipLocation.PANDEMONIUM, ShipLocation.BRIMHAVEN, 400, Requirement.PANDEMONIUM_COMPLETED),
    PANDEMONIUM_TO_CATHERBY(ShipLocation.PANDEMONIUM, ShipLocation.CATHERBY, 1200, Requirement.PANDEMONIUM_COMPLETED),
    PANDEMONIUM_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PANDEMONIUM, ShipLocation.CIVITAS_ILLA_FORTIS, 2800, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_VARLAMORE),
    PANDEMONIUM_TO_CORSAIR_COVE(ShipLocation.PANDEMONIUM, ShipLocation.CORSAIR_COVE, 800, Requirement.PANDEMONIUM_COMPLETED),
    PANDEMONIUM_TO_DEEPFIN_POINT(ShipLocation.PANDEMONIUM, ShipLocation.DEEPFIN_POINT, 2800, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_DEEPFIN_POINT),
    PANDEMONIUM_TO_LANDS_END(ShipLocation.PANDEMONIUM, ShipLocation.LANDS_END, 2600, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_KOUREND),
    PANDEMONIUM_TO_MOS_LE_HARMLESS(ShipLocation.PANDEMONIUM, ShipLocation.MOS_LE_HARMLESS, 1000, Requirement.PANDEMONIUM_COMPLETED, Requirement.CABIN_FEVER_QUEST),
    PANDEMONIUM_TO_PORT_KHAZARD(ShipLocation.PANDEMONIUM, ShipLocation.PORT_KHAZARD, 700, Requirement.PANDEMONIUM_COMPLETED),
    PANDEMONIUM_TO_PORT_PHASMATYS(ShipLocation.PANDEMONIUM, ShipLocation.PORT_PHASMATYS, 1000, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_MORYTANIA),
    PANDEMONIUM_TO_PORT_PISCARILIUS(ShipLocation.PANDEMONIUM, ShipLocation.PORT_PISCARILIUS, 2400, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_KOUREND),
    PANDEMONIUM_TO_PORT_ROBERTS(ShipLocation.PANDEMONIUM, ShipLocation.PORT_ROBERTS, 3600, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_PORT_ROBERTS),
    PANDEMONIUM_TO_PORT_TYRAS(ShipLocation.PANDEMONIUM, ShipLocation.PORT_TYRAS, 3200, Requirement.PANDEMONIUM_COMPLETED, Requirement.REGICIDE_QUEST),
    PANDEMONIUM_TO_PRIFDDINAS(ShipLocation.PANDEMONIUM, ShipLocation.PRIFDDINAS, 3800, Requirement.PANDEMONIUM_COMPLETED, Requirement.SONG_OF_THE_ELVES_QUEST),
    PANDEMONIUM_TO_SHIPYARD(ShipLocation.PANDEMONIUM, ShipLocation.SHIPYARD, 200, Requirement.PANDEMONIUM_COMPLETED, Requirement.MONKEY_MADNESS_I_FINISHED),
    PANDEMONIUM_TO_SUNSET_COAST(ShipLocation.PANDEMONIUM, ShipLocation.SUNSET_COAST, 3000, Requirement.PANDEMONIUM_COMPLETED, Requirement.VISITED_VARLAMORE),
    PORT_KHAZARD_TO_ALDARIN(ShipLocation.PORT_KHAZARD, ShipLocation.ALDARIN, 2300, Requirement.VISITED_VARLAMORE),
    PORT_KHAZARD_TO_BRIMHAVEN(ShipLocation.PORT_KHAZARD, ShipLocation.BRIMHAVEN, 400, new Requirement[0]),
    PORT_KHAZARD_TO_CATHERBY(ShipLocation.PORT_KHAZARD, ShipLocation.CATHERBY, 1600, new Requirement[0]),
    PORT_KHAZARD_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_KHAZARD, ShipLocation.CIVITAS_ILLA_FORTIS, 2200, Requirement.VISITED_VARLAMORE),
    PORT_KHAZARD_TO_CORSAIR_COVE(ShipLocation.PORT_KHAZARD, ShipLocation.CORSAIR_COVE, 600, new Requirement[0]),
    PORT_KHAZARD_TO_DEEPFIN_POINT(ShipLocation.PORT_KHAZARD, ShipLocation.DEEPFIN_POINT, 1800, Requirement.VISITED_DEEPFIN_POINT),
    PORT_KHAZARD_TO_LANDS_END(ShipLocation.PORT_KHAZARD, ShipLocation.LANDS_END, 2000, Requirement.VISITED_KOUREND),
    PORT_KHAZARD_TO_MOS_LE_HARMLESS(ShipLocation.PORT_KHAZARD, ShipLocation.MOS_LE_HARMLESS, 1100, Requirement.CABIN_FEVER_QUEST),
    PORT_KHAZARD_TO_MUSA_POINT(ShipLocation.PORT_KHAZARD, ShipLocation.MUSA_POINT, 400, new Requirement[0]),
    PORT_KHAZARD_TO_PANDEMONIUM(ShipLocation.PORT_KHAZARD, ShipLocation.PANDEMONIUM, 700, Requirement.PANDEMONIUM_COMPLETED),
    PORT_KHAZARD_TO_PORT_PHASMATYS(ShipLocation.PORT_KHAZARD, ShipLocation.PORT_PHASMATYS, 4100, Requirement.VISITED_MORYTANIA),
    PORT_KHAZARD_TO_PORT_PISCARILIUS(ShipLocation.PORT_KHAZARD, ShipLocation.PORT_PISCARILIUS, 1800, Requirement.VISITED_KOUREND),
    PORT_KHAZARD_TO_PORT_ROBERTS(ShipLocation.PORT_KHAZARD, ShipLocation.PORT_ROBERTS, 3000, Requirement.VISITED_PORT_ROBERTS),
    PORT_KHAZARD_TO_PORT_SARIM(ShipLocation.PORT_KHAZARD, ShipLocation.PORT_SARIM, 1280, new Requirement[0]),
    PORT_KHAZARD_TO_PORT_TYRAS(ShipLocation.PORT_KHAZARD, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    PORT_KHAZARD_TO_PRIFDDINAS(ShipLocation.PORT_KHAZARD, ShipLocation.PRIFDDINAS, 2800, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_KHAZARD_TO_SHIPYARD(ShipLocation.PORT_KHAZARD, ShipLocation.SHIPYARD, 1600, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_KHAZARD_TO_SUNSET_COAST(ShipLocation.PORT_KHAZARD, ShipLocation.SUNSET_COAST, 2300, Requirement.VISITED_VARLAMORE),
    PORT_PHASMATYS_TO_ALDARIN(ShipLocation.PORT_PHASMATYS, ShipLocation.ALDARIN, 4500, Requirement.VISITED_MORYTANIA, Requirement.VISITED_VARLAMORE),
    PORT_PHASMATYS_TO_BRIMHAVEN(ShipLocation.PORT_PHASMATYS, ShipLocation.BRIMHAVEN, 2900, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_CATHERBY(ShipLocation.PORT_PHASMATYS, ShipLocation.CATHERBY, 3500, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_PHASMATYS, ShipLocation.CIVITAS_ILLA_FORTIS, 4400, Requirement.VISITED_MORYTANIA, Requirement.VISITED_VARLAMORE),
    PORT_PHASMATYS_TO_CORSAIR_COVE(ShipLocation.PORT_PHASMATYS, ShipLocation.CORSAIR_COVE, 4040, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_DEEPFIN_POINT(ShipLocation.PORT_PHASMATYS, ShipLocation.DEEPFIN_POINT, 3400, Requirement.VISITED_MORYTANIA, Requirement.VISITED_DEEPFIN_POINT),
    PORT_PHASMATYS_TO_LANDS_END(ShipLocation.PORT_PHASMATYS, ShipLocation.LANDS_END, 4200, Requirement.VISITED_MORYTANIA, Requirement.VISITED_KOUREND),
    PORT_PHASMATYS_TO_MUSA_POINT(ShipLocation.PORT_PHASMATYS, ShipLocation.MUSA_POINT, 1100, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_PANDEMONIUM(ShipLocation.PORT_PHASMATYS, ShipLocation.PANDEMONIUM, 1000, Requirement.VISITED_MORYTANIA, Requirement.PANDEMONIUM_COMPLETED),
    PORT_PHASMATYS_TO_PORT_KHAZARD(ShipLocation.PORT_PHASMATYS, ShipLocation.PORT_KHAZARD, 4100, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_PORT_PISCARILIUS(ShipLocation.PORT_PHASMATYS, ShipLocation.PORT_PISCARILIUS, 4000, Requirement.VISITED_MORYTANIA, Requirement.VISITED_KOUREND),
    PORT_PHASMATYS_TO_PORT_ROBERTS(ShipLocation.PORT_PHASMATYS, ShipLocation.PORT_ROBERTS, 4600, Requirement.VISITED_MORYTANIA, Requirement.VISITED_PORT_ROBERTS),
    PORT_PHASMATYS_TO_PORT_SARIM(ShipLocation.PORT_PHASMATYS, ShipLocation.PORT_SARIM, 1300, Requirement.VISITED_MORYTANIA),
    PORT_PHASMATYS_TO_PORT_TYRAS(ShipLocation.PORT_PHASMATYS, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_MORYTANIA, Requirement.REGICIDE_QUEST),
    PORT_PHASMATYS_TO_PRIFDDINAS(ShipLocation.PORT_PHASMATYS, ShipLocation.PRIFDDINAS, 5200, Requirement.VISITED_MORYTANIA, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_PHASMATYS_TO_SHIPYARD(ShipLocation.PORT_PHASMATYS, ShipLocation.SHIPYARD, 3200, Requirement.VISITED_MORYTANIA, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_PHASMATYS_TO_SUNSET_COAST(ShipLocation.PORT_PHASMATYS, ShipLocation.SUNSET_COAST, 4500, Requirement.VISITED_MORYTANIA, Requirement.VISITED_VARLAMORE),
    PORT_PISCARILIUS_TO_ALDARIN(ShipLocation.PORT_PISCARILIUS, ShipLocation.ALDARIN, 1100, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    PORT_PISCARILIUS_TO_BRIMHAVEN(ShipLocation.PORT_PISCARILIUS, ShipLocation.BRIMHAVEN, 2000, Requirement.VISITED_KOUREND),
    PORT_PISCARILIUS_TO_CATHERBY(ShipLocation.PORT_PISCARILIUS, ShipLocation.CATHERBY, 2000, Requirement.VISITED_KOUREND),
    PORT_PISCARILIUS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_PISCARILIUS, ShipLocation.CIVITAS_ILLA_FORTIS, 1000, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    PORT_PISCARILIUS_TO_CORSAIR_COVE(ShipLocation.PORT_PISCARILIUS, ShipLocation.CORSAIR_COVE, 1500, Requirement.VISITED_KOUREND),
    PORT_PISCARILIUS_TO_DEEPFIN_POINT(ShipLocation.PORT_PISCARILIUS, ShipLocation.DEEPFIN_POINT, 1600, Requirement.VISITED_KOUREND, Requirement.VISITED_DEEPFIN_POINT),
    PORT_PISCARILIUS_TO_MOS_LE_HARMLESS(ShipLocation.PORT_PISCARILIUS, ShipLocation.MOS_LE_HARMLESS, 4200, Requirement.VISITED_KOUREND, Requirement.CABIN_FEVER_QUEST),
    PORT_PISCARILIUS_TO_MUSA_POINT(ShipLocation.PORT_PISCARILIUS, ShipLocation.MUSA_POINT, 2500, Requirement.VISITED_KOUREND),
    PORT_PISCARILIUS_TO_PANDEMONIUM(ShipLocation.PORT_PISCARILIUS, ShipLocation.PANDEMONIUM, 2400, Requirement.VISITED_KOUREND, Requirement.PANDEMONIUM_COMPLETED),
    PORT_PISCARILIUS_TO_PORT_KHAZARD(ShipLocation.PORT_PISCARILIUS, ShipLocation.PORT_KHAZARD, 1800, Requirement.VISITED_KOUREND),
    PORT_PISCARILIUS_TO_PORT_PHASMATYS(ShipLocation.PORT_PISCARILIUS, ShipLocation.PORT_PHASMATYS, 4000, Requirement.VISITED_KOUREND, Requirement.VISITED_MORYTANIA),
    PORT_PISCARILIUS_TO_PORT_ROBERTS(ShipLocation.PORT_PISCARILIUS, ShipLocation.PORT_ROBERTS, 1000, Requirement.VISITED_KOUREND, Requirement.VISITED_PORT_ROBERTS),
    PORT_PISCARILIUS_TO_PORT_TYRAS(ShipLocation.PORT_PISCARILIUS, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_KOUREND, Requirement.REGICIDE_QUEST),
    PORT_PISCARILIUS_TO_PRIFDDINAS(ShipLocation.PORT_PISCARILIUS, ShipLocation.PRIFDDINAS, 1200, Requirement.VISITED_KOUREND, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_PISCARILIUS_TO_SHIPYARD(ShipLocation.PORT_PISCARILIUS, ShipLocation.SHIPYARD, 2600, Requirement.VISITED_KOUREND, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_PISCARILIUS_TO_SUNSET_COAST(ShipLocation.PORT_PISCARILIUS, ShipLocation.SUNSET_COAST, 1100, Requirement.VISITED_KOUREND, Requirement.VISITED_VARLAMORE),
    PORT_ROBERTS_TO_ALDARIN(ShipLocation.PORT_ROBERTS, ShipLocation.ALDARIN, 1400, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_VARLAMORE),
    PORT_ROBERTS_TO_BRIMHAVEN(ShipLocation.PORT_ROBERTS, ShipLocation.BRIMHAVEN, 3200, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_CATHERBY(ShipLocation.PORT_ROBERTS, ShipLocation.CATHERBY, 3400, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_ROBERTS, ShipLocation.CIVITAS_ILLA_FORTIS, 600, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_VARLAMORE),
    PORT_ROBERTS_TO_CORSAIR_COVE(ShipLocation.PORT_ROBERTS, ShipLocation.CORSAIR_COVE, 2200, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_DEEPFIN_POINT(ShipLocation.PORT_ROBERTS, ShipLocation.DEEPFIN_POINT, 1000, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_DEEPFIN_POINT),
    PORT_ROBERTS_TO_LANDS_END(ShipLocation.PORT_ROBERTS, ShipLocation.LANDS_END, 800, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_KOUREND),
    PORT_ROBERTS_TO_MOS_LE_HARMLESS(ShipLocation.PORT_ROBERTS, ShipLocation.MOS_LE_HARMLESS, 4400, Requirement.VISITED_PORT_ROBERTS, Requirement.CABIN_FEVER_QUEST),
    PORT_ROBERTS_TO_MUSA_POINT(ShipLocation.PORT_ROBERTS, ShipLocation.MUSA_POINT, 3500, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_PANDEMONIUM(ShipLocation.PORT_ROBERTS, ShipLocation.PANDEMONIUM, 3600, Requirement.VISITED_PORT_ROBERTS, Requirement.PANDEMONIUM_COMPLETED),
    PORT_ROBERTS_TO_PORT_KHAZARD(ShipLocation.PORT_ROBERTS, ShipLocation.PORT_KHAZARD, 3000, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_PORT_PHASMATYS(ShipLocation.PORT_ROBERTS, ShipLocation.PORT_PHASMATYS, 4600, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_MORYTANIA),
    PORT_ROBERTS_TO_PORT_PISCARILIUS(ShipLocation.PORT_ROBERTS, ShipLocation.PORT_PISCARILIUS, 1000, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_KOUREND),
    PORT_ROBERTS_TO_PORT_SARIM(ShipLocation.PORT_ROBERTS, ShipLocation.PORT_SARIM, 3500, Requirement.VISITED_PORT_ROBERTS),
    PORT_ROBERTS_TO_PORT_TYRAS(ShipLocation.PORT_ROBERTS, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_PORT_ROBERTS, Requirement.REGICIDE_QUEST),
    PORT_ROBERTS_TO_PRIFDDINAS(ShipLocation.PORT_ROBERTS, ShipLocation.PRIFDDINAS, 600, Requirement.VISITED_PORT_ROBERTS, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_ROBERTS_TO_SHIPYARD(ShipLocation.PORT_ROBERTS, ShipLocation.SHIPYARD, 3600, Requirement.VISITED_PORT_ROBERTS, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_ROBERTS_TO_SUNSET_COAST(ShipLocation.PORT_ROBERTS, ShipLocation.SUNSET_COAST, 1400, Requirement.VISITED_PORT_ROBERTS, Requirement.VISITED_VARLAMORE),
    PORT_SARIM_TO_ALDARIN(ShipLocation.PORT_SARIM, ShipLocation.ALDARIN, 3100, Requirement.VISITED_VARLAMORE),
    PORT_SARIM_TO_BRIMHAVEN(ShipLocation.PORT_SARIM, ShipLocation.BRIMHAVEN, 1600, new Requirement[0]),
    PORT_SARIM_TO_CATHERBY(ShipLocation.PORT_SARIM, ShipLocation.CATHERBY, 1000, new Requirement[0]),
    PORT_SARIM_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_SARIM, ShipLocation.CIVITAS_ILLA_FORTIS, 3000, Requirement.VISITED_VARLAMORE),
    PORT_SARIM_TO_CORSAIR_COVE(ShipLocation.PORT_SARIM, ShipLocation.CORSAIR_COVE, 1200, new Requirement[0]),
    PORT_SARIM_TO_DEEPFIN_POINT(ShipLocation.PORT_SARIM, ShipLocation.DEEPFIN_POINT, 2600, Requirement.VISITED_DEEPFIN_POINT),
    PORT_SARIM_TO_MOS_LE_HARMLESS(ShipLocation.PORT_SARIM, ShipLocation.MOS_LE_HARMLESS, 1300, Requirement.CABIN_FEVER_QUEST),
    PORT_SARIM_TO_PORT_KHAZARD(ShipLocation.PORT_SARIM, ShipLocation.PORT_KHAZARD, 1280, new Requirement[0]),
    PORT_SARIM_TO_PORT_PHASMATYS(ShipLocation.PORT_SARIM, ShipLocation.PORT_PHASMATYS, 1300, Requirement.VISITED_MORYTANIA),
    PORT_SARIM_TO_PORT_ROBERTS(ShipLocation.PORT_SARIM, ShipLocation.PORT_ROBERTS, 3500, Requirement.VISITED_PORT_ROBERTS),
    PORT_SARIM_TO_PORT_TYRAS(ShipLocation.PORT_SARIM, ShipLocation.PORT_TYRAS, 3200, Requirement.REGICIDE_QUEST),
    PORT_SARIM_TO_PRIFDDINAS(ShipLocation.PORT_SARIM, ShipLocation.PRIFDDINAS, 4800, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_SARIM_TO_SHIPYARD(ShipLocation.PORT_SARIM, ShipLocation.SHIPYARD, 400, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_SARIM_TO_SUNSET_COAST(ShipLocation.PORT_SARIM, ShipLocation.SUNSET_COAST, 3100, Requirement.VISITED_VARLAMORE),
    PORT_TYRAS_TO_ALDARIN(ShipLocation.PORT_TYRAS, ShipLocation.ALDARIN, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_VARLAMORE),
    PORT_TYRAS_TO_BRIMHAVEN(ShipLocation.PORT_TYRAS, ShipLocation.BRIMHAVEN, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_CATHERBY(ShipLocation.PORT_TYRAS, ShipLocation.CATHERBY, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PORT_TYRAS, ShipLocation.CIVITAS_ILLA_FORTIS, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_VARLAMORE),
    PORT_TYRAS_TO_CORSAIR_COVE(ShipLocation.PORT_TYRAS, ShipLocation.CORSAIR_COVE, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_DEEPFIN_POINT(ShipLocation.PORT_TYRAS, ShipLocation.DEEPFIN_POINT, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_DEEPFIN_POINT),
    PORT_TYRAS_TO_LANDS_END(ShipLocation.PORT_TYRAS, ShipLocation.LANDS_END, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_KOUREND),
    PORT_TYRAS_TO_MOS_LE_HARMLESS(ShipLocation.PORT_TYRAS, ShipLocation.MOS_LE_HARMLESS, 3200, Requirement.REGICIDE_QUEST, Requirement.CABIN_FEVER_QUEST),
    PORT_TYRAS_TO_MUSA_POINT(ShipLocation.PORT_TYRAS, ShipLocation.MUSA_POINT, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_PANDEMONIUM(ShipLocation.PORT_TYRAS, ShipLocation.PANDEMONIUM, 3200, Requirement.REGICIDE_QUEST, Requirement.PANDEMONIUM_COMPLETED),
    PORT_TYRAS_TO_PORT_KHAZARD(ShipLocation.PORT_TYRAS, ShipLocation.PORT_KHAZARD, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_PORT_PHASMATYS(ShipLocation.PORT_TYRAS, ShipLocation.PORT_PHASMATYS, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_MORYTANIA),
    PORT_TYRAS_TO_PORT_PISCARILIUS(ShipLocation.PORT_TYRAS, ShipLocation.PORT_PISCARILIUS, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_KOUREND),
    PORT_TYRAS_TO_PORT_ROBERTS(ShipLocation.PORT_TYRAS, ShipLocation.PORT_ROBERTS, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_PORT_ROBERTS),
    PORT_TYRAS_TO_PORT_SARIM(ShipLocation.PORT_TYRAS, ShipLocation.PORT_SARIM, 3200, Requirement.REGICIDE_QUEST),
    PORT_TYRAS_TO_PRIFDDINAS(ShipLocation.PORT_TYRAS, ShipLocation.PRIFDDINAS, 3200, Requirement.REGICIDE_QUEST, Requirement.SONG_OF_THE_ELVES_QUEST),
    PORT_TYRAS_TO_SHIPYARD(ShipLocation.PORT_TYRAS, ShipLocation.SHIPYARD, 3200, Requirement.REGICIDE_QUEST, Requirement.MONKEY_MADNESS_I_FINISHED),
    PORT_TYRAS_TO_SUNSET_COAST(ShipLocation.PORT_TYRAS, ShipLocation.SUNSET_COAST, 3200, Requirement.REGICIDE_QUEST, Requirement.VISITED_VARLAMORE),
    PRIFDDINAS_TO_ALDARIN(ShipLocation.PRIFDDINAS, ShipLocation.ALDARIN, 1800, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_VARLAMORE),
    PRIFDDINAS_TO_BRIMHAVEN(ShipLocation.PRIFDDINAS, ShipLocation.BRIMHAVEN, 3450, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_CATHERBY(ShipLocation.PRIFDDINAS, ShipLocation.CATHERBY, 3560, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_CIVITAS_ILLA_FORTIS(ShipLocation.PRIFDDINAS, ShipLocation.CIVITAS_ILLA_FORTIS, 1700, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_VARLAMORE),
    PRIFDDINAS_TO_CORSAIR_COVE(ShipLocation.PRIFDDINAS, ShipLocation.CORSAIR_COVE, 1420, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_DEEPFIN_POINT(ShipLocation.PRIFDDINAS, ShipLocation.DEEPFIN_POINT, 1200, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_DEEPFIN_POINT),
    PRIFDDINAS_TO_LANDS_END(ShipLocation.PRIFDDINAS, ShipLocation.LANDS_END, 1500, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_KOUREND),
    PRIFDDINAS_TO_MOS_LE_HARMLESS(ShipLocation.PRIFDDINAS, ShipLocation.MOS_LE_HARMLESS, 4950, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.CABIN_FEVER_QUEST),
    PRIFDDINAS_TO_MUSA_POINT(ShipLocation.PRIFDDINAS, ShipLocation.MUSA_POINT, 4400, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_PANDEMONIUM(ShipLocation.PRIFDDINAS, ShipLocation.PANDEMONIUM, 3800, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.PANDEMONIUM_COMPLETED),
    PRIFDDINAS_TO_PORT_KHAZARD(ShipLocation.PRIFDDINAS, ShipLocation.PORT_KHAZARD, 2800, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_PORT_PHASMATYS(ShipLocation.PRIFDDINAS, ShipLocation.PORT_PHASMATYS, 5200, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_MORYTANIA),
    PRIFDDINAS_TO_PORT_PISCARILIUS(ShipLocation.PRIFDDINAS, ShipLocation.PORT_PISCARILIUS, 1200, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_KOUREND),
    PRIFDDINAS_TO_PORT_ROBERTS(ShipLocation.PRIFDDINAS, ShipLocation.PORT_ROBERTS, 600, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_PORT_ROBERTS),
    PRIFDDINAS_TO_PORT_SARIM(ShipLocation.PRIFDDINAS, ShipLocation.PORT_SARIM, 4800, Requirement.SONG_OF_THE_ELVES_QUEST),
    PRIFDDINAS_TO_PORT_TYRAS(ShipLocation.PRIFDDINAS, ShipLocation.PORT_TYRAS, 3200, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.REGICIDE_QUEST),
    PRIFDDINAS_TO_SHIPYARD(ShipLocation.PRIFDDINAS, ShipLocation.SHIPYARD, 4000, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.MONKEY_MADNESS_I_FINISHED),
    PRIFDDINAS_TO_SUNSET_COAST(ShipLocation.PRIFDDINAS, ShipLocation.SUNSET_COAST, 1800, Requirement.SONG_OF_THE_ELVES_QUEST, Requirement.VISITED_VARLAMORE),
    SHIPYARD_TO_ALDARIN(ShipLocation.SHIPYARD, ShipLocation.ALDARIN, 3100, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_VARLAMORE),
    SHIPYARD_TO_BRIMHAVEN(ShipLocation.SHIPYARD, ShipLocation.BRIMHAVEN, 400, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_CATHERBY(ShipLocation.SHIPYARD, ShipLocation.CATHERBY, 1600, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_CIVITAS_ILLA_FORTIS(ShipLocation.SHIPYARD, ShipLocation.CIVITAS_ILLA_FORTIS, 3000, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_VARLAMORE),
    SHIPYARD_TO_CORSAIR_COVE(ShipLocation.SHIPYARD, ShipLocation.CORSAIR_COVE, 800, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_DEEPFIN_POINT(ShipLocation.SHIPYARD, ShipLocation.DEEPFIN_POINT, 2800, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_DEEPFIN_POINT),
    SHIPYARD_TO_LANDS_END(ShipLocation.SHIPYARD, ShipLocation.LANDS_END, 2800, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_KOUREND),
    SHIPYARD_TO_MOS_LE_HARMLESS(ShipLocation.SHIPYARD, ShipLocation.MOS_LE_HARMLESS, 1100, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.CABIN_FEVER_QUEST),
    SHIPYARD_TO_MUSA_POINT(ShipLocation.SHIPYARD, ShipLocation.MUSA_POINT, 200, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_PANDEMONIUM(ShipLocation.SHIPYARD, ShipLocation.PANDEMONIUM, 200, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.PANDEMONIUM_COMPLETED),
    SHIPYARD_TO_PORT_KHAZARD(ShipLocation.SHIPYARD, ShipLocation.PORT_KHAZARD, 1600, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_PORT_PHASMATYS(ShipLocation.SHIPYARD, ShipLocation.PORT_PHASMATYS, 3200, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_MORYTANIA),
    SHIPYARD_TO_PORT_PISCARILIUS(ShipLocation.SHIPYARD, ShipLocation.PORT_PISCARILIUS, 2600, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_KOUREND),
    SHIPYARD_TO_PORT_ROBERTS(ShipLocation.SHIPYARD, ShipLocation.PORT_ROBERTS, 3600, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_PORT_ROBERTS),
    SHIPYARD_TO_PORT_SARIM(ShipLocation.SHIPYARD, ShipLocation.PORT_SARIM, 400, Requirement.MONKEY_MADNESS_I_FINISHED),
    SHIPYARD_TO_PORT_TYRAS(ShipLocation.SHIPYARD, ShipLocation.PORT_TYRAS, 3200, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.REGICIDE_QUEST),
    SHIPYARD_TO_PRIFDDINAS(ShipLocation.SHIPYARD, ShipLocation.PRIFDDINAS, 4000, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.SONG_OF_THE_ELVES_QUEST),
    SHIPYARD_TO_SUNSET_COAST(ShipLocation.SHIPYARD, ShipLocation.SUNSET_COAST, 3100, Requirement.MONKEY_MADNESS_I_FINISHED, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_BRIMHAVEN(ShipLocation.SUNSET_COAST, ShipLocation.BRIMHAVEN, 2500, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_CATHERBY(ShipLocation.SUNSET_COAST, ShipLocation.CATHERBY, 2500, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_CIVITAS_ILLA_FORTIS(ShipLocation.SUNSET_COAST, ShipLocation.CIVITAS_ILLA_FORTIS, 500, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_CORSAIR_COVE(ShipLocation.SUNSET_COAST, ShipLocation.CORSAIR_COVE, 2100, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_DEEPFIN_POINT(ShipLocation.SUNSET_COAST, ShipLocation.DEEPFIN_POINT, 1200, Requirement.VISITED_VARLAMORE, Requirement.VISITED_DEEPFIN_POINT),
    SUNSET_COAST_TO_LANDS_END(ShipLocation.SUNSET_COAST, ShipLocation.LANDS_END, 900, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    SUNSET_COAST_TO_MOS_LE_HARMLESS(ShipLocation.SUNSET_COAST, ShipLocation.MOS_LE_HARMLESS, 4700, Requirement.VISITED_VARLAMORE, Requirement.CABIN_FEVER_QUEST),
    SUNSET_COAST_TO_MUSA_POINT(ShipLocation.SUNSET_COAST, ShipLocation.MUSA_POINT, 3000, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_PANDEMONIUM(ShipLocation.SUNSET_COAST, ShipLocation.PANDEMONIUM, 3000, Requirement.VISITED_VARLAMORE, Requirement.PANDEMONIUM_COMPLETED),
    SUNSET_COAST_TO_PORT_KHAZARD(ShipLocation.SUNSET_COAST, ShipLocation.PORT_KHAZARD, 2300, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_PORT_PHASMATYS(ShipLocation.SUNSET_COAST, ShipLocation.PORT_PHASMATYS, 4500, Requirement.VISITED_VARLAMORE, Requirement.VISITED_MORYTANIA),
    SUNSET_COAST_TO_PORT_PISCARILIUS(ShipLocation.SUNSET_COAST, ShipLocation.PORT_PISCARILIUS, 1100, Requirement.VISITED_VARLAMORE, Requirement.VISITED_KOUREND),
    SUNSET_COAST_TO_PORT_ROBERTS(ShipLocation.SUNSET_COAST, ShipLocation.PORT_ROBERTS, 1400, Requirement.VISITED_VARLAMORE, Requirement.VISITED_PORT_ROBERTS),
    SUNSET_COAST_TO_PORT_SARIM(ShipLocation.SUNSET_COAST, ShipLocation.PORT_SARIM, 3100, Requirement.VISITED_VARLAMORE),
    SUNSET_COAST_TO_PORT_TYRAS(ShipLocation.SUNSET_COAST, ShipLocation.PORT_TYRAS, 3200, Requirement.VISITED_VARLAMORE, Requirement.REGICIDE_QUEST),
    SUNSET_COAST_TO_PRIFDDINAS(ShipLocation.SUNSET_COAST, ShipLocation.PRIFDDINAS, 1800, Requirement.VISITED_VARLAMORE, Requirement.SONG_OF_THE_ELVES_QUEST),
    SUNSET_COAST_TO_SHIPYARD(ShipLocation.SUNSET_COAST, ShipLocation.SHIPYARD, 3100, Requirement.VISITED_VARLAMORE, Requirement.MONKEY_MADNESS_I_FINISHED);

    private final ShipLocation origin;
    private final ShipLocation destination;
    private final int cost;
    private final Requirement[] requirements;
    private static final CharterShip[] VALUES;

    private CharterShip(ShipLocation origin, ShipLocation destination, int cost, Requirement ... requirements) {
        this.origin = origin;
        this.destination = destination;
        this.cost = cost;
        this.requirements = requirements;
    }

    public static int getCharterShipCost(WorldPoint source, WorldPoint destination) {
        for (CharterShip charterShip : VALUES) {
            if (!charterShip.getOrigin().getLocation().equals((Object)source) || !charterShip.getDestination().getLocation().equals((Object)destination)) continue;
            return charterShip.getCost();
        }
        return 0;
    }

    public static List<Transport> getCharterShipTransports() {
        return Arrays.stream(VALUES).filter(chartership -> chartership.getRequirements().fulfilled()).map(Static.getTransportLoader()::charterShip).collect(Collectors.toList());
    }

    public int getCost() {
        int calcCost = Static.getQuests().isFinished(Quest.CABIN_FEVER) ? (int)((double)this.cost * 0.5) : this.cost;
        IItem ring = Static.getEquipment().fromSlot(EquipmentSlot.RING);
        if (ring != null && ring.getId() == 6465) {
            return (int)((double)calcCost * 0.5);
        }
        return calcCost;
    }

    public CharterShip getNearest() {
        WorldPoint playerLocation = Static.getPlayers().getLocal().getWorldLocation();
        CharterShip nearest = null;
        int distance = Integer.MAX_VALUE;
        for (CharterShip charterShip : VALUES) {
            if (charterShip.getOrigin().getLocation().distanceTo(playerLocation) >= distance) continue;
            nearest = charterShip;
            distance = charterShip.getOrigin().getLocation().distanceTo(playerLocation);
        }
        return nearest;
    }

    public Requirements getRequirements() {
        Requirements req = new Requirements();
        if (this.requirements != null) {
            for (Requirement requirement : this.requirements) {
                if (requirement instanceof QuestRequirement) {
                    req.getQuestRequirements().add((QuestRequirement)requirement);
                    continue;
                }
                if (requirement instanceof ItemRequirement) {
                    req.getItemRequirements().add((ItemRequirement)requirement);
                    continue;
                }
                if (requirement instanceof SkillRequirement) {
                    req.getSkillRequirements().add((SkillRequirement)requirement);
                    continue;
                }
                if (requirement instanceof VarRequirement) {
                    req.getVarRequirements().add((VarRequirement)requirement);
                    continue;
                }
                req.addRequirement(requirement);
            }
        }
        req.getItemRequirements().add(new ItemRequirement(Reduction.AND, List.of(Integer.valueOf(995)), this.getCost()));
        return req;
    }

    public ShipLocation getOrigin() {
        return this.origin;
    }

    public ShipLocation getDestination() {
        return this.destination;
    }

    static {
        VALUES = CharterShip.values();
    }

    public static enum ShipLocation {
        ALDARIN(new WorldPoint(1455, 2968, 0), "Aldarin"),
        BRIMHAVEN(new WorldPoint(2760, 3238, 0), "Brimhaven"),
        CATHERBY(new WorldPoint(2792, 3414, 0), "Catherby"),
        CIVITAS_ILLA_FORTIS(new WorldPoint(1743, 3136, 0), "Civitas illa Fortis"),
        CORSAIR_COVE(new WorldPoint(2587, 2851, 0), "Corsair Cove"),
        DEEPFIN_POINT(new WorldPoint(1944, 2754, 0), "Deepfin Point"),
        LANDS_END(new WorldPoint(1496, 3403, 0), "Land's End"),
        MUSA_POINT(new WorldPoint(2953, 3158, 0), "Musa Point"),
        MOS_LE_HARMLESS(new WorldPoint(3671, 2933, 0), "Mos Le'Harmless"),
        PANDEMONIUM(new WorldPoint(3063, 3000, 0), "The Pandemonium"),
        PORT_KHAZARD(new WorldPoint(2673, 3146, 0), "Port Khazard"),
        PORT_PHASMATYS(new WorldPoint(3702, 3504, 0), "Port Phasmatys"),
        PORT_ROBERTS(new WorldPoint(1871, 3311, 0), "Port Roberts"),
        PORT_SARIM(new WorldPoint(3037, 3193, 0), "Port Sarim"),
        PORT_TYRAS(new WorldPoint(2142, 3122, 0), "Port Tyras"),
        SHIPYARD(new WorldPoint(3001, 3033, 0), "Karamja Shipyard"),
        SUNSET_COAST(new WorldPoint(1514, 2971, 0), "Sunset Coast"),
        PORT_PISCARILIUS(new WorldPoint(1808, 3679, 0), "Port Piscarilius"),
        PRIFDDINAS(new WorldPoint(2157, 3330, 0), "Prifddinas");

        private final WorldPoint location;
        private final String name;

        public IWidget getWidget() {
            IWidget parentWidget = Static.getWidgets().get(4718595);
            if (!Static.getWidgets().isVisible(parentWidget)) {
                return null;
            }
            IWidget[] dynamicChildren = parentWidget.getDynamicChildren();
            if (dynamicChildren == null || dynamicChildren.length == 0) {
                return null;
            }
            return Arrays.stream(dynamicChildren).filter(x -> x.hasAction(new String[]{this.name})).findFirst().orElse(null);
        }

        private ShipLocation(WorldPoint location, String name) {
            this.location = location;
            this.name = name;
        }

        public WorldPoint getLocation() {
            return this.location;
        }

        public String getName() {
            return this.name;
        }
    }
}

