package net.solace.loader.plugins.birdhouses.model;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import net.runelite.api.gameval.ItemID;

@RequiredArgsConstructor
@Getter
public enum SeedType {
    // Hops
    BARLEY_SEED(ItemID.BARLEY_SEED, 10),
    HAMMERSTONE_SEED(ItemID.HAMMERSTONE_HOP_SEED, 10),
    ASGARNIAN_SEED(ItemID.ASGARNIAN_HOP_SEED, 10),
    JUTE_SEED(ItemID.JUTE_SEED, 10),
    YANILLIAN_SEED(ItemID.YANILLIAN_HOP_SEED, 10),
    KRANDORIAN_SEED(ItemID.KRANDORIAN_HOP_SEED, 10),
    WILDBLOOD_SEED(ItemID.WILDBLOOD_HOP_SEED, 5),

    // Herbs
    GUAM_SEED(ItemID.GUAM_SEED, 10),
    MARRENTILL_SEED(ItemID.MARRENTILL_SEED, 10),
    TARROMIN_SEED(ItemID.TARROMIN_SEED, 10),
    HARRALANDER_SEED(ItemID.HARRALANDER_SEED, 10),
    RANARR_SEED(ItemID.RANARR_SEED, 5),
    TOADFLAX_SEED(ItemID.TOADFLAX_SEED, 5),
    IRIT_SEED(ItemID.IRIT_SEED, 5),
    AVANTOE_SEED(ItemID.AVANTOE_SEED, 5),
    KWUARM_SEED(ItemID.KWUARM_SEED, 5),
    SNAPDRAGON_SEED(ItemID.SNAPDRAGON_SEED, 5),
    CADANTINE_SEED(ItemID.CADANTINE_SEED, 5),
    LANTADYME_SEED(ItemID.LANTADYME_SEED, 5),
    DWARF_WEED(ItemID.DWARF_WEED, 5),
    TORSTOL_SEED(ItemID.TORSTOL_SEED, 5),

    // Flowers
    MARIGOLD_SEED(ItemID.MARIGOLD_SEED, 10),
    ROSEMARY_SEED(ItemID.ROSEMARY_SEED, 10),
    NASTURTIUM_SEED(ItemID.NASTURTIUM_SEED, 10),
    WOAD_SEED(ItemID.WOAD_SEED, 10),
    LIMPWURT_SEED(ItemID.LIMPWURT_SEED, 10),
    WHITE_LILY_SEED(ItemID.WHITE_LILY_SEED, 10),

    // Allotments
    POTATO_SEED(ItemID.POTATO_SEED, 10),
    ONION_SEED(ItemID.ONION_SEED, 10),
    CABBAGE_SEED(ItemID.CABBAGE_SEED, 10),
    TOMATO_SEED(ItemID.TOMATO_SEED, 10),
    SWEETCORN_SEED(ItemID.SWEETCORN_SEED, 10),
    STRAWBERRY_SEED(ItemID.STRAWBERRY_SEED, 10),
    WATERMELON_SEED(ItemID.WATERMELON_SEED, 10),
    SNAPE_GRASS_SEED(ItemID.SNAPE_GRASS_SEED, 10),
    ;

    private final int itemId;
    private final int quantity;
}
