package net.solace.api.movement.pathfinder;

import net.solace.api.movement.pathfinder.model.requirement.charges.ChargeRequirement;

public class ChargeRequirements {
    public static final ChargeRequirement ARDOUGNE_CLOAK_2 = ChargeRequirement.builder("ardougne_cloak_2").itemIds(13122).chatTrigger("You have used (?<used>\\d+) of your (?<total>\\d+) Ardougne Farm teleports for today\\.").chatTrigger("You have already used all of your available teleports for today\\. Try again tomorrow when the cape has recharged\\.").maxCharges(3).dailyReset(true).build();
    public static final ChargeRequirement ARDOUGNE_CLOAK_3 = ChargeRequirement.builder("ardougne_cloak_3").itemIds(13123).chatTrigger("You have used (?<used>\\d+) of your (?<total>\\d+) Ardougne Farm teleports for today\\.").chatTrigger("You have already used all of your available teleports for today\\. Try again tomorrow when the cape has recharged\\.").maxCharges(5).dailyReset(true).build();
    public static final ChargeRequirement CHRONICLE = ChargeRequirement.builder("chronicle").itemIds(13660).chatTrigger("Your book has (?<charges>\\d+) charges? left\\.").chatTrigger("Your book does not have any charges\\.(?<charges>)").chatTrigger("You add \\d+ charges? to your book\\. It now has (?<charges>\\d+) charges?\\.").chatTrigger("You add a single charge to your book\\. It now has (?<charges>one|two|three|four|five|six|seven|eight|nine|ten|\\d+) charges?\\.").chatTrigger("You have (?<charges>one) charge left in your book\\.").chatTrigger("Your book has run out of charges\\.(?<charges>)").maxCharges(1000).build();
    public static final ChargeRequirement RING_OF_SHADOWS = ChargeRequirement.builder("ring_of_shadows").itemIds(28327, 28329).chatTrigger("Your ring of shadows has (?<charges>\\d+) charges? remaining\\.").chatTrigger("You add (?<charges>\\d+) charges? to the ring of shadows\\.$").chatTrigger("You add \\d+ charges? to the ring of shadows\\. It now has (?<charges>\\d+) charges?\\.").chatTrigger("You fully uncharge your ring of shadows, regaining the runes used to charge it\\.(?<charges>)").chatTrigger("Your ring of shadows has run out of charges\\.(?<charges>)").maxCharges(1000).animationId(10134).build();
    public static final ChargeRequirement FREMENNIK_SEA_BOOTS_1 = ChargeRequirement.builder("fremennik_sea_boots_1").itemIds(13129).chatTrigger("You have already used your available teleports? for today\\. Try again tomorrow when the boots have recharged\\.(?<charges>)").chatTrigger("You have used your Rellekka teleport for today\\.(?<charges>)").maxCharges(1).dailyReset(true).graphicId(111).animationId(714).build();
    public static final ChargeRequirement FREMENNIK_SEA_BOOTS_2 = ChargeRequirement.builder("fremennik_sea_boots_2").itemIds(13130).chatTrigger("You have already used your available teleports? for today\\. Try again tomorrow when the boots have recharged\\.(?<charges>)").chatTrigger("You have used (?<used>\\d+) of your (?<total>\\d+) Rellekka teleports for today\\.").maxCharges(3).dailyReset(true).graphicId(111).animationId(714).build();
    public static final ChargeRequirement FREMENNIK_SEA_BOOTS_3 = ChargeRequirement.builder("fremennik_sea_boots_3").itemIds(13131).chatTrigger("You have already used your available teleports? for today\\. Try again tomorrow when the boots have recharged\\.(?<charges>)").chatTrigger("You have used (?<used>\\d+) of your (?<total>\\d+) Rellekka teleports for today\\.").maxCharges(5).dailyReset(true).graphicId(111).animationId(714).build();
    public static final ChargeRequirement PENDANT_OF_ATES = ChargeRequirement.builder("pendant_of_ates").itemIds(29893, 29892).chatTrigger("The pendant has no charges\\.").chatTrigger("The pendant has (?<charges>\\d+) charges?\\.").chatTrigger("Your pendant has (?<charges>\\d+) charges? left\\.").chatTrigger("You add .+ frozen tears? to your pendant\\. It now has (?<charges>\\d+) charges?\\.").chatTrigger("You uncharge your pendant by removing \\d+ frozen tears? from it\\.(?<charges>)").chatTrigger("Your pendant has run out of charges\\.(?<charges>)").maxCharges(1000).animationId(4018).graphicId(2754).build();
    public static final ChargeRequirement QUETZAL_WHISTLE_BASIC = ChargeRequirement.builder("quetzal_whistle_basic").itemIds(29271).chatTrigger("Your quetzal whistle has (?<charges>\\d+) charges? remaining\\.").chatTrigger("You craft yourself a basic quetzal whistle\\.(?<charges>)").chatTrigger("(?<full>)Looks like the birds are all full for now\\. Make them work a bit before feeding them again!").chatTrigger("Your whistle has no charges\\.(?<charges>)").chatTrigger("(?<full>)Some whistle charges for you!").maxCharges(5).animationId(10944).build();
    public static final ChargeRequirement QUETZAL_WHISTLE_ENHANCED = ChargeRequirement.builder("quetzal_whistle_enhanced").itemIds(29273).chatTrigger("Your quetzal whistle has (?<charges>\\d+) charges? remaining\\.").chatTrigger("(?<full>)Looks like the birds are all full for now\\. Make them work a bit before feeding them again!").chatTrigger("Your whistle has no charges\\.(?<charges>)").chatTrigger("(?<full>)Some whistle charges for you!").maxCharges(20).animationId(10944).build();
    public static final ChargeRequirement QUETZAL_WHISTLE_PERFECTED = ChargeRequirement.builder("quetzal_whistle_perfected").itemIds(29275).chatTrigger("Your quetzal whistle has (?<charges>\\d+) charges? remaining\\.").chatTrigger("(?<full>)Looks like the birds are all full for now\\. Make them work a bit before feeding them again!").chatTrigger("Your whistle has no charges\\.(?<charges>)").chatTrigger("(?<full>)Some whistle charges for you!").maxCharges(50).animationId(10944).build();
    public static final ChargeRequirement WESTERN_BANNER_3 = ChargeRequirement.builder("western_banner_3").itemIds(13143).chatTrigger("You have already used your available teleports? for today\\. Try again tomorrow after the (?:standard|banner) has recharged\\.(?<charges>)").maxCharges(1).animationId(714).graphicId(111).dailyReset(true).build();
    public static final ChargeRequirement[] ALL = new ChargeRequirement[]{ARDOUGNE_CLOAK_2, ARDOUGNE_CLOAK_3, CHRONICLE, RING_OF_SHADOWS, FREMENNIK_SEA_BOOTS_1, FREMENNIK_SEA_BOOTS_2, FREMENNIK_SEA_BOOTS_3, PENDANT_OF_ATES, QUETZAL_WHISTLE_BASIC, QUETZAL_WHISTLE_ENHANCED, QUETZAL_WHISTLE_PERFECTED, WESTERN_BANNER_3};
}

