package net.solace.api.widgets;

import net.runelite.api.widgets.WidgetInfo;

@Deprecated(forRemoval=true)
public class InterfaceAddress {
    public static InterfaceAddress BANK_PIN_1 = new InterfaceAddress(213, 16);
    public static InterfaceAddress BANK_PIN_2 = new InterfaceAddress(213, 18);
    public static InterfaceAddress BANK_PIN_3 = new InterfaceAddress(213, 20);
    public static InterfaceAddress BANK_PIN_4 = new InterfaceAddress(213, 22);
    public static InterfaceAddress BANK_PIN_5 = new InterfaceAddress(213, 24);
    public static InterfaceAddress BANK_PIN_6 = new InterfaceAddress(213, 26);
    public static InterfaceAddress BANK_PIN_7 = new InterfaceAddress(213, 28);
    public static InterfaceAddress BANK_PIN_8 = new InterfaceAddress(213, 30);
    public static InterfaceAddress BANK_PIN_9 = new InterfaceAddress(213, 32);
    public static InterfaceAddress BANK_PIN_10 = new InterfaceAddress(213, 34);
    public static InterfaceAddress COMBAT_STYLE_ONE = InterfaceAddress.fromPackedId(38862854);
    public static InterfaceAddress COMBAT_STYLE_TWO = InterfaceAddress.fromPackedId(38862858);
    public static InterfaceAddress COMBAT_STYLE_THREE = InterfaceAddress.fromPackedId(38862862);
    public static InterfaceAddress COMBAT_STYLE_FOUR = InterfaceAddress.fromPackedId(38862866);
    public static InterfaceAddress COMBAT_SPELL_BOX = InterfaceAddress.fromPackedId(38862876);
    public static InterfaceAddress COMBAT_DEFENSIVE_SPELL_BOX = InterfaceAddress.fromPackedId(38862871);
    public static InterfaceAddress FOSSIL_MUSHROOM_HOUSE = new InterfaceAddress(608, 4);
    public static InterfaceAddress FOSSIL_MUSHROOM_VALLEY = new InterfaceAddress(608, 8);
    public static InterfaceAddress FOSSIL_MUSHROOM_SWAMP = new InterfaceAddress(608, 12);
    public static InterfaceAddress FOSSIL_MUSHROOM_MEADOW = new InterfaceAddress(608, 16);
    public static InterfaceAddress PRAYER_THICK_SKIN = new InterfaceAddress(541, 9);
    public static InterfaceAddress PRAYER_BURST_OF_STRENGTH = new InterfaceAddress(541, 10);
    public static InterfaceAddress PRAYER_CLARITY_OF_THOUGHT = new InterfaceAddress(541, 11);
    public static InterfaceAddress PRAYER_SHARP_EYE = new InterfaceAddress(541, 27);
    public static InterfaceAddress PRAYER_MYSTIC_WILL = new InterfaceAddress(541, 30);
    public static InterfaceAddress PRAYER_ROCK_SKIN = new InterfaceAddress(541, 12);
    public static InterfaceAddress PRAYER_SUPERHUMAN_STRENGTH = new InterfaceAddress(541, 13);
    public static InterfaceAddress PRAYER_IMPROVED_REFLEXES = new InterfaceAddress(541, 14);
    public static InterfaceAddress PRAYER_RAPID_RESTORE = new InterfaceAddress(541, 15);
    public static InterfaceAddress PRAYER_RAPID_HEAL = new InterfaceAddress(541, 16);
    public static InterfaceAddress PRAYER_PROTECT_ITEM = new InterfaceAddress(541, 17);
    public static InterfaceAddress PRAYER_HAWK_EYE = new InterfaceAddress(541, 28);
    public static InterfaceAddress PRAYER_MYSTIC_LORE = new InterfaceAddress(541, 31);
    public static InterfaceAddress PRAYER_STEEL_SKIN = new InterfaceAddress(541, 18);
    public static InterfaceAddress PRAYER_ULTIMATE_STRENGTH = new InterfaceAddress(541, 19);
    public static InterfaceAddress PRAYER_INCREDIBLE_REFLEXES = new InterfaceAddress(541, 20);
    public static InterfaceAddress PRAYER_PROTECT_FROM_MAGIC = new InterfaceAddress(541, 21);
    public static InterfaceAddress PRAYER_PROTECT_FROM_MISSILES = new InterfaceAddress(541, 22);
    public static InterfaceAddress PRAYER_PROTECT_FROM_MELEE = new InterfaceAddress(541, 23);
    public static InterfaceAddress PRAYER_EAGLE_EYE = new InterfaceAddress(541, 29);
    public static InterfaceAddress PRAYER_MYSTIC_MIGHT = new InterfaceAddress(541, 32);
    public static InterfaceAddress PRAYER_RETRIBUTION = new InterfaceAddress(541, 24);
    public static InterfaceAddress PRAYER_REDEMPTION = new InterfaceAddress(541, 25);
    public static InterfaceAddress PRAYER_SMITE = new InterfaceAddress(541, 26);
    public static InterfaceAddress PRAYER_PRESERVE = new InterfaceAddress(541, 37);
    public static InterfaceAddress PRAYER_CHIVALRY = new InterfaceAddress(541, 34);
    public static InterfaceAddress PRAYER_PIETY = new InterfaceAddress(541, 35);
    public static InterfaceAddress PRAYER_RIGOUR = new InterfaceAddress(541, 33);
    public static InterfaceAddress PRAYER_AUGURY = new InterfaceAddress(541, 36);
    public static InterfaceAddress DIALOG_NOTIFICATION_CONTINUE = new InterfaceAddress(229, 1);
    public static InterfaceAddress DIALOG_OPTION_OPTION1 = new InterfaceAddress(219, 1);
    public static InterfaceAddress DIALOG2_SPRITE_CONTINUE = new InterfaceAddress(11, 4);
    public static InterfaceAddress EQUIPMENT_HELMET = new InterfaceAddress(387, 15);
    public static InterfaceAddress EQUIPMENT_CAPE = new InterfaceAddress(387, 16);
    public static InterfaceAddress EQUIPMENT_AMULET = new InterfaceAddress(387, 17);
    public static InterfaceAddress EQUIPMENT_WEAPON = new InterfaceAddress(387, 18);
    public static InterfaceAddress EQUIPMENT_BODY = new InterfaceAddress(387, 19);
    public static InterfaceAddress EQUIPMENT_SHIELD = new InterfaceAddress(387, 20);
    public static InterfaceAddress EQUIPMENT_LEGS = new InterfaceAddress(387, 21);
    public static InterfaceAddress EQUIPMENT_GLOVES = new InterfaceAddress(387, 22);
    public static InterfaceAddress EQUIPMENT_BOOTS = new InterfaceAddress(387, 23);
    public static InterfaceAddress EQUIPMENT_RING = new InterfaceAddress(387, 24);
    public static InterfaceAddress EQUIPMENT_AMMO = new InterfaceAddress(387, 25);
    public static InterfaceAddress SMITHING_ANVIL_ARROW_HEADS = new InterfaceAddress(312, 30);
    public static InterfaceAddress SMITHING_ANVIL_AXE = new InterfaceAddress(312, 14);
    public static InterfaceAddress SMITHING_ANVIL_BATTLE_AXE = new InterfaceAddress(312, 17);
    public static InterfaceAddress SMITHING_ANVIL_BOLTS = new InterfaceAddress(312, 34);
    public static InterfaceAddress SMITHING_ANVIL_CHAIN_BODY = new InterfaceAddress(312, 19);
    public static InterfaceAddress SMITHING_ANVIL_CLAWS = new InterfaceAddress(312, 18);
    public static InterfaceAddress SMITHING_ANVIL_DAGGER = new InterfaceAddress(312, 9);
    public static InterfaceAddress SMITHING_ANVIL_DART_TIPS = new InterfaceAddress(312, 29);
    public static InterfaceAddress SMITHING_ANVIL_EXCLUSIVE1 = new InterfaceAddress(312, 28);
    public static InterfaceAddress SMITHING_ANVIL_EXCLUSIVE2 = new InterfaceAddress(312, 32);
    public static InterfaceAddress SMITHING_ANVIL_FULL_HELM = new InterfaceAddress(312, 25);
    public static InterfaceAddress SMITHING_ANVIL_JAVELIN_HEADS = new InterfaceAddress(312, 33);
    public static InterfaceAddress SMITHING_ANVIL_KITE_SHIELD = new InterfaceAddress(312, 27);
    public static InterfaceAddress SMITHING_ANVIL_KNIVES = new InterfaceAddress(312, 31);
    public static InterfaceAddress SMITHING_ANVIL_LIMBS = new InterfaceAddress(312, 35);
    public static InterfaceAddress SMITHING_ANVIL_LONG_SWORD = new InterfaceAddress(312, 12);
    public static InterfaceAddress SMITHING_ANVIL_MACE = new InterfaceAddress(312, 15);
    public static InterfaceAddress SMITHING_ANVIL_MED_HELM = new InterfaceAddress(312, 24);
    public static InterfaceAddress SMITHING_ANVIL_NAILS = new InterfaceAddress(312, 23);
    public static InterfaceAddress SMITHING_ANVIL_PLATE_BODY = new InterfaceAddress(312, 22);
    public static InterfaceAddress SMITHING_ANVIL_PLATE_LEGS = new InterfaceAddress(312, 20);
    public static InterfaceAddress SMITHING_ANVIL_PLATE_SKIRT = new InterfaceAddress(312, 21);
    public static InterfaceAddress SMITHING_ANVIL_SCIMITAR = new InterfaceAddress(312, 11);
    public static InterfaceAddress SMITHING_ANVIL_SQ_SHIELD = new InterfaceAddress(312, 26);
    public static InterfaceAddress SMITHING_ANVIL_SWORD = new InterfaceAddress(312, 10);
    public static InterfaceAddress SMITHING_ANVIL_TWO_H_SWORD = new InterfaceAddress(312, 13);
    public static InterfaceAddress SMITHING_ANVIL_WARHAMMER = new InterfaceAddress(312, 16);
    public static InterfaceAddress SPELLBOOK = new InterfaceAddress(218, 0);
    public static InterfaceAddress SPELLBOOK_FILTERED_BOUNDS = new InterfaceAddress(218, 3);
    public static InterfaceAddress SPELL_LUMBRIDGE_HOME_TELEPORT = new InterfaceAddress(14286854);
    public static InterfaceAddress SPELL_EDGEVILLE_HOME_TELEPORT = new InterfaceAddress(14286956);
    public static InterfaceAddress SPELL_LUNAR_HOME_TELEPORT = new InterfaceAddress(14286957);
    public static InterfaceAddress SPELL_ARCEUUS_HOME_TELEPORT = new InterfaceAddress(14287001);
    public static InterfaceAddress SPELL_KOUREND_HOME_TELEPORT = new InterfaceAddress(14286852);
    public static InterfaceAddress SPELL_CATHERBY_HOME_TELEPORT = new InterfaceAddress(14286853);
    public static InterfaceAddress SPELL_LUNAR_FERTILE_SOIL = new InterfaceAddress(14286982);
    public static InterfaceAddress SPELL_WIND_STRIKE = new InterfaceAddress(218, 8);
    public static InterfaceAddress SPELL_CONFUSE = new InterfaceAddress(218, 9);
    public static InterfaceAddress SPELL_ENCHANT_CROSSBOW_BOLT = new InterfaceAddress(218, 10);
    public static InterfaceAddress SPELL_WATER_STRIKE = new InterfaceAddress(218, 11);
    public static InterfaceAddress SPELL_LVL_1_ENCHANT = new InterfaceAddress(218, 13);
    public static InterfaceAddress SPELL_EARTH_STRIKE = new InterfaceAddress(218, 14);
    public static InterfaceAddress SPELL_WEAKEN = new InterfaceAddress(218, 15);
    public static InterfaceAddress SPELL_FIRE_STRIKE = new InterfaceAddress(218, 16);
    public static InterfaceAddress SPELL_BONES_TO_BANANAS = new InterfaceAddress(218, 17);
    public static InterfaceAddress SPELL_WIND_BOLT = new InterfaceAddress(218, 18);
    public static InterfaceAddress SPELL_CURSE = new InterfaceAddress(218, 19);
    public static InterfaceAddress SPELL_BIND = new InterfaceAddress(218, 20);
    public static InterfaceAddress SPELL_LOW_LEVEL_ALCHEMY = new InterfaceAddress(218, 21);
    public static InterfaceAddress SPELL_WATER_BOLT = new InterfaceAddress(218, 22);
    public static InterfaceAddress SPELL_VARROCK_TELEPORT = new InterfaceAddress(218, 23);
    public static InterfaceAddress SPELL_LVL_2_ENCHANT = new InterfaceAddress(218, 24);
    public static InterfaceAddress SPELL_EARTH_BOLT = new InterfaceAddress(218, 25);
    public static InterfaceAddress SPELL_LUMBRIDGE_TELEPORT = new InterfaceAddress(218, 26);
    public static InterfaceAddress SPELL_TELEKINETIC_GRAB = new InterfaceAddress(218, 27);
    public static InterfaceAddress SPELL_FIRE_BOLT = new InterfaceAddress(218, 28);
    public static InterfaceAddress SPELL_FALADOR_TELEPORT = new InterfaceAddress(218, 29);
    public static InterfaceAddress SPELL_CRUMBLE_UNDEAD = new InterfaceAddress(218, 30);
    public static InterfaceAddress SPELL_TELEPORT_TO_HOUSE = new InterfaceAddress(218, 31);
    public static InterfaceAddress SPELL_WIND_BLAST = new InterfaceAddress(218, 32);
    public static InterfaceAddress SPELL_SUPERHEAT_ITEM = new InterfaceAddress(218, 33);
    public static InterfaceAddress SPELL_CAMELOT_TELEPORT = new InterfaceAddress(218, 34);
    public static InterfaceAddress SPELL_WATER_BLAST = new InterfaceAddress(218, 35);
    public static InterfaceAddress SPELL_LVL_3_ENCHANT = new InterfaceAddress(218, 37);
    public static InterfaceAddress SPELL_IBAN_BLAST = new InterfaceAddress(218, 38);
    public static InterfaceAddress SPELL_SNARE = new InterfaceAddress(218, 39);
    public static InterfaceAddress SPELL_MAGIC_DART = new InterfaceAddress(218, 40);
    public static InterfaceAddress SPELL_ARDOUGNE_TELEPORT = new InterfaceAddress(218, 41);
    public static InterfaceAddress SPELL_EARTH_BLAST = new InterfaceAddress(218, 42);
    public static InterfaceAddress SPELL_HIGH_LEVEL_ALCHEMY = new InterfaceAddress(218, 44);
    public static InterfaceAddress SPELL_CHARGE_WATER_ORB = new InterfaceAddress(218, 45);
    public static InterfaceAddress SPELL_LVL_4_ENCHANT = new InterfaceAddress(218, 46);
    public static InterfaceAddress SPELL_WATCHTOWER_TELEPORT = new InterfaceAddress(218, 47);
    public static InterfaceAddress SPELL_CIVITAS_ILLA_FORTIS_TELEPORT = new InterfaceAddress(218, 43);
    public static InterfaceAddress SPELL_FIRE_BLAST = new InterfaceAddress(218, 48);
    public static InterfaceAddress SPELL_CHARGE_EARTH_ORB = new InterfaceAddress(218, 49);
    public static InterfaceAddress SPELL_BONES_TO_PEACHES = new InterfaceAddress(218, 50);
    public static InterfaceAddress SPELL_SARADOMIN_STRIKE = new InterfaceAddress(218, 51);
    public static InterfaceAddress SPELL_CLAWS_OF_GUTHIX = new InterfaceAddress(218, 52);
    public static InterfaceAddress SPELL_FLAMES_OF_ZAMORAK = new InterfaceAddress(218, 53);
    public static InterfaceAddress SPELL_TROLLHEIM_TELEPORT = new InterfaceAddress(218, 54);
    public static InterfaceAddress SPELL_WIND_WAVE = new InterfaceAddress(218, 55);
    public static InterfaceAddress SPELL_CHARGE_FIRE_ORB = new InterfaceAddress(218, 56);
    public static InterfaceAddress SPELL_TELEPORT_TO_APE_ATOLL = new InterfaceAddress(218, 57);
    public static InterfaceAddress SPELL_WATER_WAVE = new InterfaceAddress(218, 58);
    public static InterfaceAddress SPELL_CHARGE_AIR_ORB = new InterfaceAddress(218, 59);
    public static InterfaceAddress SPELL_VULNERABILITY = new InterfaceAddress(218, 60);
    public static InterfaceAddress SPELL_LVL_5_ENCHANT = new InterfaceAddress(218, 61);
    public static InterfaceAddress SPELL_TELEPORT_TO_KOUREND = new InterfaceAddress(218, 36);
    public static InterfaceAddress SPELL_EARTH_WAVE = new InterfaceAddress(218, 62);
    public static InterfaceAddress SPELL_ENFEEBLE = new InterfaceAddress(218, 63);
    public static InterfaceAddress SPELL_FIRE_WAVE = new InterfaceAddress(218, 65);
    public static InterfaceAddress SPELL_ENTANGLE = new InterfaceAddress(218, 66);
    public static InterfaceAddress SPELL_TELEOTHER_LUMBRIDGE = new InterfaceAddress(218, 64);
    public static InterfaceAddress SPELL_STUN = new InterfaceAddress(218, 67);
    public static InterfaceAddress SPELL_CHARGE = new InterfaceAddress(218, 68);
    public static InterfaceAddress SPELL_WIND_SURGE = new InterfaceAddress(218, 69);
    public static InterfaceAddress SPELL_TELEOTHER_FALADOR = new InterfaceAddress(218, 70);
    public static InterfaceAddress SPELL_WATER_SURGE = new InterfaceAddress(218, 71);
    public static InterfaceAddress SPELL_TELE_BLOCK = new InterfaceAddress(218, 72);
    public static InterfaceAddress SPELL_LVL_6_ENCHANT = new InterfaceAddress(218, 74);
    public static InterfaceAddress SPELL_TELEOTHER_CAMELOT = new InterfaceAddress(218, 75);
    public static InterfaceAddress SPELL_EARTH_SURGE = new InterfaceAddress(218, 76);
    public static InterfaceAddress SPELL_LVL_7_ENCHANT = new InterfaceAddress(218, 77);
    public static InterfaceAddress SPELL_FIRE_SURGE = new InterfaceAddress(218, 78);
    public static InterfaceAddress SPELL_TELE_BOAT_TO_ME = new InterfaceAddress(218, 79);
    public static InterfaceAddress SPELL_TELE_ME_TO_BOAT = new InterfaceAddress(218, 80);
    public static InterfaceAddress SPELL_MONSTER_INSPECT = new InterfaceAddress(218, 195);
    public static InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT2 = new InterfaceAddress(218, 73);
    public static InterfaceAddress SPELL_ICE_RUSH = new InterfaceAddress(218, 81);
    public static InterfaceAddress SPELL_ICE_BLITZ = new InterfaceAddress(218, 82);
    public static InterfaceAddress SPELL_ICE_BURST = new InterfaceAddress(218, 83);
    public static InterfaceAddress SPELL_ICE_BARRAGE = new InterfaceAddress(218, 84);
    public static InterfaceAddress SPELL_BLOOD_RUSH = new InterfaceAddress(218, 85);
    public static InterfaceAddress SPELL_BLOOD_BLITZ = new InterfaceAddress(218, 86);
    public static InterfaceAddress SPELL_BLOOD_BURST = new InterfaceAddress(218, 87);
    public static InterfaceAddress SPELL_BLOOD_BARRAGE = new InterfaceAddress(218, 88);
    public static InterfaceAddress SPELL_SMOKE_RUSH = new InterfaceAddress(218, 89);
    public static InterfaceAddress SPELL_SMOKE_BLITZ = new InterfaceAddress(218, 90);
    public static InterfaceAddress SPELL_SMOKE_BURST = new InterfaceAddress(218, 91);
    public static InterfaceAddress SPELL_SMOKE_BARRAGE = new InterfaceAddress(218, 92);
    public static InterfaceAddress SPELL_SHADOW_RUSH = new InterfaceAddress(218, 93);
    public static InterfaceAddress SPELL_SHADOW_BLITZ = new InterfaceAddress(218, 94);
    public static InterfaceAddress SPELL_SHADOW_BURST = new InterfaceAddress(218, 95);
    public static InterfaceAddress SPELL_SHADOW_BARRAGE = new InterfaceAddress(218, 96);
    public static InterfaceAddress SPELL_PADDEWWA_TELEPORT = new InterfaceAddress(218, 97);
    public static InterfaceAddress SPELL_SENNTISTEN_TELEPORT = new InterfaceAddress(218, 98);
    public static InterfaceAddress SPELL_KHARYRLL_TELEPORT = new InterfaceAddress(218, 99);
    public static InterfaceAddress SPELL_LASSAR_TELEPORT = new InterfaceAddress(218, 100);
    public static InterfaceAddress SPELL_DAREEYAK_TELEPORT = new InterfaceAddress(218, 101);
    public static InterfaceAddress SPELL_CARRALLANGER_TELEPORT = new InterfaceAddress(218, 102);
    public static InterfaceAddress SPELL_ANNAKARL_TELEPORT = new InterfaceAddress(218, 103);
    public static InterfaceAddress SPELL_GHORROCK_TELEPORT = new InterfaceAddress(218, 104);
    public static InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT = new InterfaceAddress(218, 73);
    public static InterfaceAddress SPELL_VENGEANCE_OTHER = new InterfaceAddress(218, 143);
    public static InterfaceAddress SPELL_VENGEANCE = new InterfaceAddress(218, 144);
    public static InterfaceAddress SPELL_BOUNTY_TARGET_TELEPORT3 = new InterfaceAddress(218, 73);
    public static InterfaceAddress SPELL_BAKE_PIE = new InterfaceAddress(218, 107);
    public static InterfaceAddress SPELL_CURE_PLANT = new InterfaceAddress(218, 108);
    public static InterfaceAddress SPELL_MONSTER_EXAMINE = new InterfaceAddress(218, 109);
    public static InterfaceAddress SPELL_NPC_CONTACT = new InterfaceAddress(218, 110);
    public static InterfaceAddress SPELL_CURE_OTHER = new InterfaceAddress(218, 111);
    public static InterfaceAddress SPELL_HUMIDIFY = new InterfaceAddress(218, 112);
    public static InterfaceAddress SPELL_MOONCLAN_TELEPORT = new InterfaceAddress(218, 113);
    public static InterfaceAddress SPELL_TELE_GROUP_MOONCLAN = new InterfaceAddress(218, 114);
    public static InterfaceAddress SPELL_CURE_ME = new InterfaceAddress(218, 115);
    public static InterfaceAddress SPELL_HUNTER_KIT = new InterfaceAddress(218, 116);
    public static InterfaceAddress SPELL_WATERBIRTH_TELEPORT = new InterfaceAddress(218, 117);
    public static InterfaceAddress SPELL_TELE_GROUP_WATERBIRTH = new InterfaceAddress(218, 118);
    public static InterfaceAddress SPELL_CURE_GROUP = new InterfaceAddress(218, 119);
    public static InterfaceAddress SPELL_STAT_SPY = new InterfaceAddress(218, 120);
    public static InterfaceAddress SPELL_BARBARIAN_TELEPORT = new InterfaceAddress(218, 121);
    public static InterfaceAddress SPELL_TELE_GROUP_BARBARIAN = new InterfaceAddress(218, 122);
    public static InterfaceAddress SPELL_SUPERGLASS_MAKE = new InterfaceAddress(218, 123);
    public static InterfaceAddress SPELL_TAN_LEATHER = new InterfaceAddress(218, 124);
    public static InterfaceAddress SPELL_KHAZARD_TELEPORT = new InterfaceAddress(218, 125);
    public static InterfaceAddress SPELL_TELE_GROUP_KHAZARD = new InterfaceAddress(218, 126);
    public static InterfaceAddress SPELL_DREAM = new InterfaceAddress(218, 127);
    public static InterfaceAddress SPELL_STRING_JEWELLERY = new InterfaceAddress(218, 128);
    public static InterfaceAddress SPELL_STAT_RESTORE_POT_SHARE = new InterfaceAddress(218, 129);
    public static InterfaceAddress SPELL_MAGIC_IMBUE = new InterfaceAddress(218, 130);
    public static InterfaceAddress SPELL_FERTILE_SOIL = new InterfaceAddress(218, 131);
    public static InterfaceAddress SPELL_BOOST_POTION_SHARE = new InterfaceAddress(218, 132);
    public static InterfaceAddress SPELL_FISHING_GUILD_TELEPORT = new InterfaceAddress(218, 133);
    public static InterfaceAddress SPELL_TELE_GROUP_FISHING_GUILD = new InterfaceAddress(218, 134);
    public static InterfaceAddress SPELL_PLANK_MAKE = new InterfaceAddress(218, 135);
    public static InterfaceAddress SPELL_CATHERBY_TELEPORT = new InterfaceAddress(218, 136);
    public static InterfaceAddress SPELL_TELE_GROUP_CATHERBY = new InterfaceAddress(218, 137);
    public static InterfaceAddress SPELL_RECHARGE_DRAGONSTONE = new InterfaceAddress(218, 138);
    public static InterfaceAddress SPELL_ICE_PLATEAU_TELEPORT = new InterfaceAddress(218, 139);
    public static InterfaceAddress SPELL_TELE_GROUP_ICE_PLATEAU = new InterfaceAddress(218, 140);
    public static InterfaceAddress SPELL_ENERGY_TRANSFER = new InterfaceAddress(218, 141);
    public static InterfaceAddress SPELL_HEAL_OTHER = new InterfaceAddress(218, 142);
    public static InterfaceAddress SPELL_HEAL_GROUP = new InterfaceAddress(218, 145);
    public static InterfaceAddress SPELL_SPELLBOOK_SWAP = new InterfaceAddress(218, 146);
    public static InterfaceAddress SPELL_GEOMANCY = new InterfaceAddress(218, 147);
    public static InterfaceAddress SPELL_SPIN_FLAX = new InterfaceAddress(218, 148);
    public static InterfaceAddress SPELL_OURANIA_TELEPORT = new InterfaceAddress(218, 149);
    public static InterfaceAddress SPELL_TOOLTIP = new InterfaceAddress(218, 190);
    public static InterfaceAddress SPELL_BASIC_REANIMATION = new InterfaceAddress(218, 151);
    public static InterfaceAddress SPELL_ARCEUUS_LIBRARY_TELEPORT = new InterfaceAddress(218, 152);
    public static InterfaceAddress SPELL_ADEPT_REANIMATION = new InterfaceAddress(218, 153);
    public static InterfaceAddress SPELL_EXPERT_REANIMATION = new InterfaceAddress(218, 154);
    public static InterfaceAddress SPELL_MASTER_REANIMATION = new InterfaceAddress(218, 155);
    public static InterfaceAddress SPELL_DRAYNOR_MANOR_TELEPORT = new InterfaceAddress(218, 156);
    public static InterfaceAddress SPELL_MIND_ALTAR_TELEPORT = new InterfaceAddress(218, 158);
    public static InterfaceAddress SPELL_RESPAWN_TELEPORT = new InterfaceAddress(218, 159);
    public static InterfaceAddress SPELL_SALVE_GRAVEYARD_TELEPORT = new InterfaceAddress(218, 160);
    public static InterfaceAddress SPELL_FENKENSTRAINS_CASTLE_TELEPORT = new InterfaceAddress(218, 161);
    public static InterfaceAddress SPELL_WEST_ARDOUGNE_TELEPORT = new InterfaceAddress(218, 162);
    public static InterfaceAddress SPELL_HARMONY_ISLAND_TELEPORT = new InterfaceAddress(218, 163);
    public static InterfaceAddress SPELL_CEMETERY_TELEPORT = new InterfaceAddress(218, 164);
    public static InterfaceAddress SPELL_RESURRECT_CROPS = new InterfaceAddress(218, 165);
    public static InterfaceAddress SPELL_BARROWS_TELEPORT = new InterfaceAddress(218, 166);
    public static InterfaceAddress SPELL_APE_ATOLL_TELEPORT = new InterfaceAddress(218, 167);
    public static InterfaceAddress SPELL_BATTLEFRONT_TELEPORT = new InterfaceAddress(218, 168);
    public static InterfaceAddress SPELL_INFERIOR_DEMONBANE = new InterfaceAddress(218, 169);
    public static InterfaceAddress SPELL_SUPERIOR_DEMONBANE = new InterfaceAddress(218, 170);
    public static InterfaceAddress SPELL_DARK_DEMONBANE = new InterfaceAddress(218, 171);
    public static InterfaceAddress SPELL_MARK_OF_DARKNESS = new InterfaceAddress(218, 172);
    public static InterfaceAddress SPELL_GHOSTLY_GRASP = new InterfaceAddress(218, 173);
    public static InterfaceAddress SPELL_SKELETAL_GRASP = new InterfaceAddress(218, 174);
    public static InterfaceAddress SPELL_UNDEAD_GRASP = new InterfaceAddress(218, 175);
    public static InterfaceAddress SPELL_WARD_OF_ARCEUUS = new InterfaceAddress(218, 176);
    public static InterfaceAddress SPELL_LESSER_CORRUPTION = new InterfaceAddress(218, 177);
    public static InterfaceAddress SPELL_GREATER_CORRUPTION = new InterfaceAddress(218, 178);
    public static InterfaceAddress SPELL_DEMONIC_OFFERING = new InterfaceAddress(218, 179);
    public static InterfaceAddress SPELL_SINISTER_OFFERING = new InterfaceAddress(218, 180);
    public static InterfaceAddress SPELL_DEGRIME = new InterfaceAddress(218, 181);
    public static InterfaceAddress SPELL_SHADOW_VEIL = new InterfaceAddress(218, 182);
    public static InterfaceAddress SPELL_VILE_VIGOUR = new InterfaceAddress(218, 183);
    public static InterfaceAddress SPELL_DARK_LURE = new InterfaceAddress(218, 184);
    public static InterfaceAddress SPELL_DEATH_CHARGE = new InterfaceAddress(218, 185);
    public static InterfaceAddress SPELL_RESURRECT_LESSER_GHOST = new InterfaceAddress(218, 186);
    public static InterfaceAddress SPELL_RESURRECT_LESSER_SKELETON = new InterfaceAddress(218, 187);
    public static InterfaceAddress SPELL_RESURRECT_LESSER_ZOMBIE = new InterfaceAddress(218, 188);
    public static InterfaceAddress SPELL_RESURRECT_SUPERIOR_GHOST = new InterfaceAddress(218, 189);
    public static InterfaceAddress SPELL_RESURRECT_SUPERIOR_SKELETON = new InterfaceAddress(218, 190);
    public static InterfaceAddress SPELL_RESURRECT_SUPERIOR_ZOMBIE = new InterfaceAddress(218, 191);
    public static InterfaceAddress SPELL_RESURRECT_GREATER_GHOST = new InterfaceAddress(218, 192);
    public static InterfaceAddress SPELL_RESURRECT_GREATER_SKELETON = new InterfaceAddress(218, 193);
    public static InterfaceAddress SPELL_RESURRECT_GREATER_ZOMBIE = new InterfaceAddress(218, 194);
    public static InterfaceAddress MINIMAP_SPEC_CLICKBOX = new InterfaceAddress(160, 35);
    public static InterfaceAddress MINIGAME_DIALOG_CONTINUE = new InterfaceAddress(229, 2);
    public static InterfaceAddress LEVEL_UP_CONTINUE = new InterfaceAddress(233, 3);
    public static InterfaceAddress DEPOSIT_BOX_DEPOSIT_INVENTORY = new InterfaceAddress(192, 29);
    public static InterfaceAddress DEPOSIT_BOX_DEPOSIT_EQUIPMENT = new InterfaceAddress(192, 30);
    public static InterfaceAddress DEPOSIT_BOX_DEPOSIT_LOOT_BAG = new InterfaceAddress(192, 31);
    public static InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_ONE = new InterfaceAddress(192, 34);
    public static InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_FIVE = new InterfaceAddress(192, 35);
    public static InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_TEN = new InterfaceAddress(192, 36);
    public static InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_X = new InterfaceAddress(192, 37);
    public static InterfaceAddress DEPOSIT_INVENTORY_QUANTITY_ALL = new InterfaceAddress(192, 38);
    public static InterfaceAddress SAILING_VIEW_COMBAT_OPTIONS = new InterfaceAddress(937, 1);
    public static InterfaceAddress SAILING_BOAT_NAME = new InterfaceAddress(937, 2);
    public static InterfaceAddress SAILING_BOAT_HEALTH_BAR = new InterfaceAddress(937, 3);
    public static InterfaceAddress SAILING_TAB_BAR = new InterfaceAddress(937, 4);
    public static InterfaceAddress SAILING_BOAT_PANEL_TITLE = new InterfaceAddress(937, 6);
    public static InterfaceAddress SAILING_BOAT_CREW_PANEL = new InterfaceAddress(937, 7);
    public static InterfaceAddress SAILING_BOAT_STAT_PANEL = new InterfaceAddress(937, 15);
    public static InterfaceAddress SAILING_BOAT_FACILITIES_PANEL = new InterfaceAddress(937, 22);
    public static InterfaceAddress SAILING_BOAT_CONTROLS = new InterfaceAddress(937, 25);
    public static InterfaceAddress SAILING_BOAT_CREW_CAPACITY = new InterfaceAddress(937, 37);
    public static InterfaceAddress SAILING_BOAT_CREW_TOGGLES = new InterfaceAddress(937, 38);
    private final int group;
    private final int child;

    public InterfaceAddress(int packedId) {
        this(packedId >> 16, packedId & 0xFFFF);
    }

    public static InterfaceAddress fromPackedId(int packedId) {
        return new InterfaceAddress(packedId);
    }

    public static InterfaceAddress fromWidgetInfo(WidgetInfo widgetInfo) {
        return new InterfaceAddress(widgetInfo.getGroupId(), widgetInfo.getChildId());
    }

    public int getPackedId() {
        return this.group << 16 | this.child;
    }

    public InterfaceAddress(int group, int child) {
        this.group = group;
        this.child = child;
    }

    public int getGroup() {
        return this.group;
    }

    public int getChild() {
        return this.child;
    }
}

